// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals_audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelApprovalRequest = `-- name: CancelApprovalRequest :one
UPDATE public.approval_requests
SET status = 'cancelled',
    updated_at = timezone('utc', now())
WHERE id = $1 AND status IN ('draft', 'pending')
RETURNING id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at
`

func (q *Queries) CancelApprovalRequest(ctx context.Context, id pgtype.UUID) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, cancelApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countApprovalPolicies = `-- name: CountApprovalPolicies :one
SELECT count(*) FROM public.approval_policies
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::text IS NULL OR module = $2::text)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
`

type CountApprovalPoliciesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Module           pgtype.Text `json:"module"`
	IsActive         pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountApprovalPolicies(ctx context.Context, arg CountApprovalPoliciesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalPolicies, arg.BusinessEntityID, arg.Module, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovalRequests = `-- name: CountApprovalRequests :one
SELECT count(*) FROM public.approval_requests
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR module = $4::text)
  AND ($5::text IS NULL OR request_type = $5::text)
  AND ($6::uuid IS NULL OR requested_by_user_id = $6::uuid)
`

type CountApprovalRequestsParams struct {
	BusinessEntityID  pgtype.UUID `json:"business_entity_id"`
	BranchID          pgtype.UUID `json:"branch_id"`
	Status            pgtype.Text `json:"status"`
	Module            pgtype.Text `json:"module"`
	RequestType       pgtype.Text `json:"request_type"`
	RequestedByUserID pgtype.UUID `json:"requested_by_user_id"`
}

func (q *Queries) CountApprovalRequests(ctx context.Context, arg CountApprovalRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalRequests,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.Status,
		arg.Module,
		arg.RequestType,
		arg.RequestedByUserID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApprovedDecisions = `-- name: CountApprovedDecisions :one
SELECT count(*) FROM public.approval_request_approvers
WHERE approval_request_id = $1 AND decision = 'approved'
`

func (q *Queries) CountApprovedDecisions(ctx context.Context, approvalRequestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedDecisions, approvalRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM public.audit_logs
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::uuid IS NULL OR entity_id = $2::uuid)
  AND ($3::uuid IS NULL OR user_id = $3::uuid)
  AND ($4::text IS NULL OR action_type = $4::text)
  AND ($5::text IS NULL OR module = $5::text)
  AND ($6::timestamptz IS NULL OR event_time >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR event_time <= $7::timestamptz)
`

type CountAuditLogsParams struct {
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ActionType pgtype.Text        `json:"action_type"`
	Module     pgtype.Text        `json:"module"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.ActionType,
		arg.Module,
		arg.DateFrom,
		arg.DateTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsForEntity = `-- name: CountAuditLogsForEntity :one
SELECT count(*) FROM public.audit_logs
WHERE entity_type = $1 AND entity_id = $2
`

type CountAuditLogsForEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) CountAuditLogsForEntity(ctx context.Context, arg CountAuditLogsForEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsForEntity, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovers = `-- name: CountPendingApprovers :one
SELECT count(*) FROM public.approval_request_approvers
WHERE approval_request_id = $1 AND decision IS NULL
`

func (q *Queries) CountPendingApprovers(ctx context.Context, approvalRequestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovers, approvalRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalPolicy = `-- name: CreateApprovalPolicy :one
INSERT INTO public.approval_policies (
    business_entity_id, code, name, module, request_type,
    min_approvers, prevent_self_approval, approver_role_id,
    auto_approve_below_amount, expiry_hours, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_entity_id, code, name, module, request_type, min_approvers, prevent_self_approval, approver_role_id, auto_approve_below_amount, expiry_hours, is_active, created_at, updated_at
`

type CreateApprovalPolicyParams struct {
	BusinessEntityID       pgtype.UUID    `json:"business_entity_id"`
	Code                   string         `json:"code"`
	Name                   string         `json:"name"`
	Module                 string         `json:"module"`
	RequestType            string         `json:"request_type"`
	MinApprovers           int16          `json:"min_approvers"`
	PreventSelfApproval    bool           `json:"prevent_self_approval"`
	ApproverRoleID         pgtype.UUID    `json:"approver_role_id"`
	AutoApproveBelowAmount pgtype.Numeric `json:"auto_approve_below_amount"`
	ExpiryHours            pgtype.Int4    `json:"expiry_hours"`
	IsActive               bool           `json:"is_active"`
}

func (q *Queries) CreateApprovalPolicy(ctx context.Context, arg CreateApprovalPolicyParams) (ApprovalPolicy, error) {
	row := q.db.QueryRow(ctx, createApprovalPolicy,
		arg.BusinessEntityID,
		arg.Code,
		arg.Name,
		arg.Module,
		arg.RequestType,
		arg.MinApprovers,
		arg.PreventSelfApproval,
		arg.ApproverRoleID,
		arg.AutoApproveBelowAmount,
		arg.ExpiryHours,
		arg.IsActive,
	)
	var i ApprovalPolicy
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.Module,
		&i.RequestType,
		&i.MinApprovers,
		&i.PreventSelfApproval,
		&i.ApproverRoleID,
		&i.AutoApproveBelowAmount,
		&i.ExpiryHours,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApprovalRequest = `-- name: CreateApprovalRequest :one
INSERT INTO public.approval_requests (
    business_entity_id, branch_id, approval_policy_id,
    module, request_type, source_record_type, source_record_id,
    requested_by_user_id, assigned_to_user_id, status,
    payload_snapshot_json
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at
`

type CreateApprovalRequestParams struct {
	BusinessEntityID    pgtype.UUID `json:"business_entity_id"`
	BranchID            pgtype.UUID `json:"branch_id"`
	ApprovalPolicyID    pgtype.UUID `json:"approval_policy_id"`
	Module              string      `json:"module"`
	RequestType         string      `json:"request_type"`
	SourceRecordType    string      `json:"source_record_type"`
	SourceRecordID      pgtype.UUID `json:"source_record_id"`
	RequestedByUserID   pgtype.UUID `json:"requested_by_user_id"`
	AssignedToUserID    pgtype.UUID `json:"assigned_to_user_id"`
	Status              string      `json:"status"`
	PayloadSnapshotJson []byte      `json:"payload_snapshot_json"`
}

func (q *Queries) CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, createApprovalRequest,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ApprovalPolicyID,
		arg.Module,
		arg.RequestType,
		arg.SourceRecordType,
		arg.SourceRecordID,
		arg.RequestedByUserID,
		arg.AssignedToUserID,
		arg.Status,
		arg.PayloadSnapshotJson,
	)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApprovalRequestApprover = `-- name: CreateApprovalRequestApprover :one
INSERT INTO public.approval_request_approvers (
    approval_request_id, user_id
) VALUES ($1, $2)
RETURNING id, approval_request_id, user_id, decision, decided_at, decision_reason, created_at
`

type CreateApprovalRequestApproverParams struct {
	ApprovalRequestID pgtype.UUID `json:"approval_request_id"`
	UserID            pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateApprovalRequestApprover(ctx context.Context, arg CreateApprovalRequestApproverParams) (ApprovalRequestApprover, error) {
	row := q.db.QueryRow(ctx, createApprovalRequestApprover, arg.ApprovalRequestID, arg.UserID)
	var i ApprovalRequestApprover
	err := row.Scan(
		&i.ID,
		&i.ApprovalRequestID,
		&i.UserID,
		&i.Decision,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getApprovalPolicy = `-- name: GetApprovalPolicy :one
SELECT id, business_entity_id, code, name, module, request_type, min_approvers, prevent_self_approval, approver_role_id, auto_approve_below_amount, expiry_hours, is_active, created_at, updated_at FROM public.approval_policies WHERE id = $1
`

func (q *Queries) GetApprovalPolicy(ctx context.Context, id pgtype.UUID) (ApprovalPolicy, error) {
	row := q.db.QueryRow(ctx, getApprovalPolicy, id)
	var i ApprovalPolicy
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.Module,
		&i.RequestType,
		&i.MinApprovers,
		&i.PreventSelfApproval,
		&i.ApproverRoleID,
		&i.AutoApproveBelowAmount,
		&i.ExpiryHours,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalPolicyByCode = `-- name: GetApprovalPolicyByCode :one
SELECT id, business_entity_id, code, name, module, request_type, min_approvers, prevent_self_approval, approver_role_id, auto_approve_below_amount, expiry_hours, is_active, created_at, updated_at FROM public.approval_policies 
WHERE business_entity_id = $1 AND code = $2
`

type GetApprovalPolicyByCodeParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Code             string      `json:"code"`
}

func (q *Queries) GetApprovalPolicyByCode(ctx context.Context, arg GetApprovalPolicyByCodeParams) (ApprovalPolicy, error) {
	row := q.db.QueryRow(ctx, getApprovalPolicyByCode, arg.BusinessEntityID, arg.Code)
	var i ApprovalPolicy
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.Module,
		&i.RequestType,
		&i.MinApprovers,
		&i.PreventSelfApproval,
		&i.ApproverRoleID,
		&i.AutoApproveBelowAmount,
		&i.ExpiryHours,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at FROM public.approval_requests WHERE id = $1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id pgtype.UUID) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuditLogsForEntity = `-- name: GetAuditLogsForEntity :many
SELECT id, event_time, user_id, module, action_type, entity_type, entity_id, scope_type, scope_id, result_status, reason, summary_text, before_snapshot_json, after_snapshot_json, related_approval_request_id, created_at FROM public.audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY event_time DESC
LIMIT $3 OFFSET $4
`

type GetAuditLogsForEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) GetAuditLogsForEntity(ctx context.Context, arg GetAuditLogsForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsForEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventTime,
			&i.UserID,
			&i.Module,
			&i.ActionType,
			&i.EntityType,
			&i.EntityID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ResultStatus,
			&i.Reason,
			&i.SummaryText,
			&i.BeforeSnapshotJson,
			&i.AfterSnapshotJson,
			&i.RelatedApprovalRequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO public.audit_logs (
    event_time, user_id, module, action_type,
    entity_type, entity_id, scope_type, scope_id,
    result_status, reason, summary_text,
    before_snapshot_json, after_snapshot_json,
    related_approval_request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, event_time, user_id, module, action_type, entity_type, entity_id, scope_type, scope_id, result_status, reason, summary_text, before_snapshot_json, after_snapshot_json, related_approval_request_id, created_at
`

type InsertAuditLogParams struct {
	EventTime                pgtype.Timestamptz `json:"event_time"`
	UserID                   pgtype.UUID        `json:"user_id"`
	Module                   string             `json:"module"`
	ActionType               string             `json:"action_type"`
	EntityType               string             `json:"entity_type"`
	EntityID                 pgtype.UUID        `json:"entity_id"`
	ScopeType                string             `json:"scope_type"`
	ScopeID                  pgtype.UUID        `json:"scope_id"`
	ResultStatus             string             `json:"result_status"`
	Reason                   pgtype.Text        `json:"reason"`
	SummaryText              string             `json:"summary_text"`
	BeforeSnapshotJson       []byte             `json:"before_snapshot_json"`
	AfterSnapshotJson        []byte             `json:"after_snapshot_json"`
	RelatedApprovalRequestID pgtype.UUID        `json:"related_approval_request_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.EventTime,
		arg.UserID,
		arg.Module,
		arg.ActionType,
		arg.EntityType,
		arg.EntityID,
		arg.ScopeType,
		arg.ScopeID,
		arg.ResultStatus,
		arg.Reason,
		arg.SummaryText,
		arg.BeforeSnapshotJson,
		arg.AfterSnapshotJson,
		arg.RelatedApprovalRequestID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EventTime,
		&i.UserID,
		&i.Module,
		&i.ActionType,
		&i.EntityType,
		&i.EntityID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ResultStatus,
		&i.Reason,
		&i.SummaryText,
		&i.BeforeSnapshotJson,
		&i.AfterSnapshotJson,
		&i.RelatedApprovalRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovalPolicies = `-- name: ListApprovalPolicies :many


SELECT id, business_entity_id, code, name, module, request_type, min_approvers, prevent_self_approval, approver_role_id, auto_approve_below_amount, expiry_hours, is_active, created_at, updated_at FROM public.approval_policies
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::text IS NULL OR module = $4::text)
  AND ($5::boolean IS NULL OR is_active = $5::boolean)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListApprovalPoliciesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Module           pgtype.Text `json:"module"`
	IsActive         pgtype.Bool `json:"is_active"`
}

// backend/db/queries/approvals_audit.sql
// =============================================================================
// Approvals + Audit Domain Queries
// =============================================================================
func (q *Queries) ListApprovalPolicies(ctx context.Context, arg ListApprovalPoliciesParams) ([]ApprovalPolicy, error) {
	rows, err := q.db.Query(ctx, listApprovalPolicies,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.Module,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalPolicy{}
	for rows.Next() {
		var i ApprovalPolicy
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.Code,
			&i.Name,
			&i.Module,
			&i.RequestType,
			&i.MinApprovers,
			&i.PreventSelfApproval,
			&i.ApproverRoleID,
			&i.AutoApproveBelowAmount,
			&i.ExpiryHours,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRequestApprovers = `-- name: ListApprovalRequestApprovers :many
SELECT id, approval_request_id, user_id, decision, decided_at, decision_reason, created_at FROM public.approval_request_approvers
WHERE approval_request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListApprovalRequestApprovers(ctx context.Context, approvalRequestID pgtype.UUID) ([]ApprovalRequestApprover, error) {
	rows, err := q.db.Query(ctx, listApprovalRequestApprovers, approvalRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequestApprover{}
	for rows.Next() {
		var i ApprovalRequestApprover
		if err := rows.Scan(
			&i.ID,
			&i.ApprovalRequestID,
			&i.UserID,
			&i.Decision,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRequests = `-- name: ListApprovalRequests :many
SELECT id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at FROM public.approval_requests
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::uuid IS NULL OR branch_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
  AND ($6::text IS NULL OR module = $6::text)
  AND ($7::text IS NULL OR request_type = $7::text)
  AND ($8::uuid IS NULL OR requested_by_user_id = $8::uuid)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListApprovalRequestsParams struct {
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
	BusinessEntityID  pgtype.UUID `json:"business_entity_id"`
	BranchID          pgtype.UUID `json:"branch_id"`
	Status            pgtype.Text `json:"status"`
	Module            pgtype.Text `json:"module"`
	RequestType       pgtype.Text `json:"request_type"`
	RequestedByUserID pgtype.UUID `json:"requested_by_user_id"`
}

func (q *Queries) ListApprovalRequests(ctx context.Context, arg ListApprovalRequestsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalRequests,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.Status,
		arg.Module,
		arg.RequestType,
		arg.RequestedByUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.ApprovalPolicyID,
			&i.Module,
			&i.RequestType,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.RequestedByUserID,
			&i.AssignedToUserID,
			&i.Status,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecisionReason,
			&i.PayloadSnapshotJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, event_time, user_id, module, action_type, entity_type, entity_id, scope_type, scope_id, result_status, reason, summary_text, before_snapshot_json, after_snapshot_json, related_approval_request_id, created_at FROM public.audit_logs
WHERE ($3::text IS NULL OR entity_type = $3::text)
  AND ($4::uuid IS NULL OR entity_id = $4::uuid)
  AND ($5::uuid IS NULL OR user_id = $5::uuid)
  AND ($6::text IS NULL OR action_type = $6::text)
  AND ($7::text IS NULL OR module = $7::text)
  AND ($8::timestamptz IS NULL OR event_time >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR event_time <= $9::timestamptz)
ORDER BY event_time DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ActionType pgtype.Text        `json:"action_type"`
	Module     pgtype.Text        `json:"module"`
	DateFrom   pgtype.Timestamptz `json:"date_from"`
	DateTo     pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.ActionType,
		arg.Module,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventTime,
			&i.UserID,
			&i.Module,
			&i.ActionType,
			&i.EntityType,
			&i.EntityID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ResultStatus,
			&i.Reason,
			&i.SummaryText,
			&i.BeforeSnapshotJson,
			&i.AfterSnapshotJson,
			&i.RelatedApprovalRequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordApproverDecision = `-- name: RecordApproverDecision :one
UPDATE public.approval_request_approvers
SET decision = $2,
    decided_at = timezone('utc', now()),
    decision_reason = $3
WHERE approval_request_id = $1 AND user_id = $4 AND decision IS NULL
RETURNING id, approval_request_id, user_id, decision, decided_at, decision_reason, created_at
`

type RecordApproverDecisionParams struct {
	ApprovalRequestID pgtype.UUID `json:"approval_request_id"`
	Decision          pgtype.Text `json:"decision"`
	DecisionReason    pgtype.Text `json:"decision_reason"`
	UserID            pgtype.UUID `json:"user_id"`
}

func (q *Queries) RecordApproverDecision(ctx context.Context, arg RecordApproverDecisionParams) (ApprovalRequestApprover, error) {
	row := q.db.QueryRow(ctx, recordApproverDecision,
		arg.ApprovalRequestID,
		arg.Decision,
		arg.DecisionReason,
		arg.UserID,
	)
	var i ApprovalRequestApprover
	err := row.Scan(
		&i.ID,
		&i.ApprovalRequestID,
		&i.UserID,
		&i.Decision,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateApprovalPolicy = `-- name: UpdateApprovalPolicy :one
UPDATE public.approval_policies
SET name = COALESCE($1::text, name),
    min_approvers = COALESCE($2::smallint, min_approvers),
    prevent_self_approval = COALESCE($3::boolean, prevent_self_approval),
    approver_role_id = COALESCE($4::uuid, approver_role_id),
    auto_approve_below_amount = COALESCE($5::numeric, auto_approve_below_amount),
    expiry_hours = COALESCE($6::integer, expiry_hours),
    is_active = COALESCE($7::boolean, is_active),
    updated_at = timezone('utc', now())
WHERE id = $8::uuid
RETURNING id, business_entity_id, code, name, module, request_type, min_approvers, prevent_self_approval, approver_role_id, auto_approve_below_amount, expiry_hours, is_active, created_at, updated_at
`

type UpdateApprovalPolicyParams struct {
	Name                   pgtype.Text    `json:"name"`
	MinApprovers           pgtype.Int2    `json:"min_approvers"`
	PreventSelfApproval    pgtype.Bool    `json:"prevent_self_approval"`
	ApproverRoleID         pgtype.UUID    `json:"approver_role_id"`
	AutoApproveBelowAmount pgtype.Numeric `json:"auto_approve_below_amount"`
	ExpiryHours            pgtype.Int4    `json:"expiry_hours"`
	IsActive               pgtype.Bool    `json:"is_active"`
	ID                     pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateApprovalPolicy(ctx context.Context, arg UpdateApprovalPolicyParams) (ApprovalPolicy, error) {
	row := q.db.QueryRow(ctx, updateApprovalPolicy,
		arg.Name,
		arg.MinApprovers,
		arg.PreventSelfApproval,
		arg.ApproverRoleID,
		arg.AutoApproveBelowAmount,
		arg.ExpiryHours,
		arg.IsActive,
		arg.ID,
	)
	var i ApprovalPolicy
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.Module,
		&i.RequestType,
		&i.MinApprovers,
		&i.PreventSelfApproval,
		&i.ApproverRoleID,
		&i.AutoApproveBelowAmount,
		&i.ExpiryHours,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApprovalRequestStatus = `-- name: UpdateApprovalRequestStatus :one
UPDATE public.approval_requests
SET status = $2,
    decided_at = CASE WHEN $2 IN ('approved', 'rejected') THEN timezone('utc', now()) ELSE decided_at END,
    decision_reason = COALESCE($3, decision_reason),
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'pending'
RETURNING id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at
`

type UpdateApprovalRequestStatusParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	DecisionReason pgtype.Text `json:"decision_reason"`
}

func (q *Queries) UpdateApprovalRequestStatus(ctx context.Context, arg UpdateApprovalRequestStatusParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, updateApprovalRequestStatus, arg.ID, arg.Status, arg.DecisionReason)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
