// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :one
INSERT INTO public.user_role_scope_assignments (
    user_id, role_id, scope_type, scope_id
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, role_id, scope_type, scope_id, created_at, updated_at
`

type AssignRoleToUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	RoleID    pgtype.UUID `json:"role_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (UserRoleScopeAssignment, error) {
	row := q.db.QueryRow(ctx, assignRoleToUser,
		arg.UserID,
		arg.RoleID,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i UserRoleScopeAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkUserPermission = `-- name: CheckUserPermission :one
SELECT EXISTS (
    SELECT 1
    FROM public.user_role_scope_assignments ursa
    JOIN public.roles r ON r.id = ursa.role_id
    JOIN public.role_permissions rp ON rp.role_id = r.id
    JOIN public.permissions p ON p.id = rp.permission_id
    WHERE ursa.user_id = $1
      AND p.key = $2
      AND r.is_active = true
) AS has_permission
`

type CheckUserPermissionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Key    string      `json:"key"`
}

// Returns true if user has a specific permission through any active role
func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.UserID, arg.Key)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const checkUserPermissionInScope = `-- name: CheckUserPermissionInScope :one
SELECT EXISTS (
    SELECT 1
    FROM public.user_role_scope_assignments ursa
    JOIN public.roles r ON r.id = ursa.role_id
    JOIN public.role_permissions rp ON rp.role_id = r.id
    JOIN public.permissions p ON p.id = rp.permission_id
    WHERE ursa.user_id = $1
      AND p.key = $2
      AND r.is_active = true
      AND (
        ursa.scope_type = 'deployment'
        OR (ursa.scope_type = 'business_entity' AND ursa.scope_id = $3)
        OR (ursa.scope_type = 'branch' AND ursa.scope_id = $4)
        OR (ursa.scope_type = 'project' AND ursa.scope_id = $5)
      )
) AS has_permission
`

type CheckUserPermissionInScopeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Key       string      `json:"key"`
	ScopeID   pgtype.UUID `json:"scope_id"`
	ScopeID_2 pgtype.UUID `json:"scope_id_2"`
	ScopeID_3 pgtype.UUID `json:"scope_id_3"`
}

// Returns true if user has permission at deployment scope or at the target business_entity/branch/project scope.
func (q *Queries) CheckUserPermissionInScope(ctx context.Context, arg CheckUserPermissionInScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermissionInScope,
		arg.UserID,
		arg.Key,
		arg.ScopeID,
		arg.ScopeID_2,
		arg.ScopeID_3,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}

const getPermission = `-- name: GetPermission :one
SELECT id, key, module, description, created_at FROM public.permissions WHERE id = $1
`

func (q *Queries) GetPermission(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Module,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, code, name, description, is_active, created_at, updated_at FROM public.roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many

SELECT DISTINCT p.id, p.key, p.module, p.description, p.created_at, ursa.scope_type, ursa.scope_id
FROM public.user_role_scope_assignments ursa
JOIN public.roles r ON r.id = ursa.role_id
JOIN public.role_permissions rp ON rp.role_id = r.id
JOIN public.permissions p ON p.id = rp.permission_id
WHERE ursa.user_id = $1
  AND r.is_active = true
ORDER BY p.key ASC
`

type GetUserPermissionsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Module      string             `json:"module"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ScopeType   string             `json:"scope_type"`
	ScopeID     pgtype.UUID        `json:"scope_id"`
}

// =============================================================================
// Permission Resolution (for middleware + /me/permissions)
// =============================================================================
// Returns all distinct permission keys for a user through their role assignments
func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPermissionsRow{}
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Module,
			&i.Description,
			&i.CreatedAt,
			&i.ScopeType,
			&i.ScopeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleAssignment = `-- name: GetUserRoleAssignment :one
SELECT id, user_id, role_id, scope_type, scope_id, created_at, updated_at FROM public.user_role_scope_assignments WHERE id = $1
`

func (q *Queries) GetUserRoleAssignment(ctx context.Context, id pgtype.UUID) (UserRoleScopeAssignment, error) {
	row := q.db.QueryRow(ctx, getUserRoleAssignment, id)
	var i UserRoleScopeAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many

SELECT id, key, module, description, created_at FROM public.permissions
WHERE ($1::text IS NULL OR module = $1::text)
ORDER BY key ASC
`

// =============================================================================
// Permissions
// =============================================================================
func (q *Queries) ListPermissions(ctx context.Context, module pgtype.Text) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions, module)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Module,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many

SELECT p.id, p.key, p.module, p.description, p.created_at FROM public.permissions p
JOIN public.role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
ORDER BY p.key ASC
`

// =============================================================================
// Role Permissions
// =============================================================================
func (q *Queries) ListRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Module,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many


SELECT id, code, name, description, is_active, created_at, updated_at FROM public.roles
WHERE ($1::boolean IS NULL OR is_active = $1::boolean)
ORDER BY code ASC
`

// =============================================================================
// Authorization Domain Queries
// =============================================================================
// =============================================================================
// Roles
// =============================================================================
func (q *Queries) ListRoles(ctx context.Context, isActive pgtype.Bool) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleAssignments = `-- name: ListUserRoleAssignments :many

SELECT id, user_id, role_id, scope_type, scope_id, created_at, updated_at FROM public.user_role_scope_assignments
WHERE user_id = $1
ORDER BY created_at DESC
`

// =============================================================================
// User Role Scope Assignments
// =============================================================================
func (q *Queries) ListUserRoleAssignments(ctx context.Context, userID pgtype.UUID) ([]UserRoleScopeAssignment, error) {
	rows, err := q.db.Query(ctx, listUserRoleAssignments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoleScopeAssignment{}
	for rows.Next() {
		var i UserRoleScopeAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :one
DELETE FROM public.user_role_scope_assignments WHERE id = $1
RETURNING id, user_id, role_id, scope_type, scope_id, created_at, updated_at
`

func (q *Queries) RemoveRoleFromUser(ctx context.Context, id pgtype.UUID) (UserRoleScopeAssignment, error) {
	row := q.db.QueryRow(ctx, removeRoleFromUser, id)
	var i UserRoleScopeAssignment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
