// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_structure.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBranches = `-- name: CountBranches :one
SELECT COUNT(*) FROM branches
WHERE business_entity_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
`

type CountBranchesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	IsActive         pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountBranches(ctx context.Context, arg CountBranchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBranches, arg.BusinessEntityID, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBranchesByBusinessEntity = `-- name: CountBranchesByBusinessEntity :one
SELECT COUNT(*) FROM branches WHERE business_entity_id = $1 AND is_active = true
`

func (q *Queries) CountBranchesByBusinessEntity(ctx context.Context, businessEntityID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBranchesByBusinessEntity, businessEntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBusinessEntities = `-- name: CountBusinessEntities :one
SELECT COUNT(*) FROM business_entities
WHERE ($1::boolean IS NULL OR is_active = $1)
`

func (q *Queries) CountBusinessEntities(ctx context.Context, isActive pgtype.Bool) (int64, error) {
	row := q.db.QueryRow(ctx, countBusinessEntities, isActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    business_entity_id, code, name, display_name, country, city,
    address_text, phone, email, status, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, business_entity_id, code, name, display_name, country, city, address_text, phone, email, status, is_active, notes, created_at, updated_at
`

type CreateBranchParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	DisplayName      pgtype.Text `json:"display_name"`
	Country          pgtype.Text `json:"country"`
	City             pgtype.Text `json:"city"`
	AddressText      pgtype.Text `json:"address_text"`
	Phone            pgtype.Text `json:"phone"`
	Email            pgtype.Text `json:"email"`
	Status           string      `json:"status"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.BusinessEntityID,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.Country,
		arg.City,
		arg.AddressText,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.Notes,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.Country,
		&i.City,
		&i.AddressText,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessEntity = `-- name: CreateBusinessEntity :one
INSERT INTO business_entities (
    code, name, display_name, default_currency, country,
    registration_no, tax_no, status, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, code, name, display_name, default_currency, country, registration_no, tax_no, status, is_active, notes, created_at, updated_at
`

type CreateBusinessEntityParams struct {
	Code            string      `json:"code"`
	Name            string      `json:"name"`
	DisplayName     pgtype.Text `json:"display_name"`
	DefaultCurrency string      `json:"default_currency"`
	Country         pgtype.Text `json:"country"`
	RegistrationNo  pgtype.Text `json:"registration_no"`
	TaxNo           pgtype.Text `json:"tax_no"`
	Status          string      `json:"status"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) CreateBusinessEntity(ctx context.Context, arg CreateBusinessEntityParams) (BusinessEntity, error) {
	row := q.db.QueryRow(ctx, createBusinessEntity,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.DefaultCurrency,
		arg.Country,
		arg.RegistrationNo,
		arg.TaxNo,
		arg.Status,
		arg.Notes,
	)
	var i BusinessEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.DefaultCurrency,
		&i.Country,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBranch = `-- name: DeactivateBranch :exec
UPDATE branches SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateBranch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateBranch, id)
	return err
}

const deactivateBusinessEntity = `-- name: DeactivateBusinessEntity :exec
UPDATE business_entities SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateBusinessEntity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateBusinessEntity, id)
	return err
}

const getBranch = `-- name: GetBranch :one
SELECT id, business_entity_id, code, name, display_name, country, city, address_text, phone, email, status, is_active, notes, created_at, updated_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id pgtype.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.Country,
		&i.City,
		&i.AddressText,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranchByCode = `-- name: GetBranchByCode :one
SELECT id, business_entity_id, code, name, display_name, country, city, address_text, phone, email, status, is_active, notes, created_at, updated_at FROM branches WHERE business_entity_id = $1 AND code = $2
`

type GetBranchByCodeParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Code             string      `json:"code"`
}

func (q *Queries) GetBranchByCode(ctx context.Context, arg GetBranchByCodeParams) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByCode, arg.BusinessEntityID, arg.Code)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.Country,
		&i.City,
		&i.AddressText,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessEntity = `-- name: GetBusinessEntity :one
SELECT id, code, name, display_name, default_currency, country, registration_no, tax_no, status, is_active, notes, created_at, updated_at FROM business_entities WHERE id = $1
`

func (q *Queries) GetBusinessEntity(ctx context.Context, id pgtype.UUID) (BusinessEntity, error) {
	row := q.db.QueryRow(ctx, getBusinessEntity, id)
	var i BusinessEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.DefaultCurrency,
		&i.Country,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessEntityByCode = `-- name: GetBusinessEntityByCode :one
SELECT id, code, name, display_name, default_currency, country, registration_no, tax_no, status, is_active, notes, created_at, updated_at FROM business_entities WHERE code = $1
`

func (q *Queries) GetBusinessEntityByCode(ctx context.Context, code string) (BusinessEntity, error) {
	row := q.db.QueryRow(ctx, getBusinessEntityByCode, code)
	var i BusinessEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.DefaultCurrency,
		&i.Country,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many

SELECT id, business_entity_id, code, name, display_name, country, city, address_text, phone, email, status, is_active, notes, created_at, updated_at FROM branches
WHERE business_entity_id = $1
  AND ($2::boolean IS NULL OR is_active = $2)
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListBranchesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	IsActive         pgtype.Bool `json:"is_active"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// ============================================================================
// BRANCH
// ============================================================================
func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches,
		arg.BusinessEntityID,
		arg.IsActive,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.Code,
			&i.Name,
			&i.DisplayName,
			&i.Country,
			&i.City,
			&i.AddressText,
			&i.Phone,
			&i.Email,
			&i.Status,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessEntities = `-- name: ListBusinessEntities :many

SELECT id, code, name, display_name, default_currency, country, registration_no, tax_no, status, is_active, notes, created_at, updated_at FROM business_entities
WHERE ($1::boolean IS NULL OR is_active = $1)
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListBusinessEntitiesParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Offset   int32       `json:"offset"`
	Limit    int32       `json:"limit"`
}

// backend/db/queries/business_structure.sql
func (q *Queries) ListBusinessEntities(ctx context.Context, arg ListBusinessEntitiesParams) ([]BusinessEntity, error) {
	rows, err := q.db.Query(ctx, listBusinessEntities, arg.IsActive, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessEntity{}
	for rows.Next() {
		var i BusinessEntity
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DisplayName,
			&i.DefaultCurrency,
			&i.Country,
			&i.RegistrationNo,
			&i.TaxNo,
			&i.Status,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches SET
    code = COALESCE($1::text, code),
    name = COALESCE($2::text, name),
    display_name = COALESCE($3::text, display_name),
    country = COALESCE($4::text, country),
    city = COALESCE($5::text, city),
    address_text = COALESCE($6::text, address_text),
    phone = COALESCE($7::text, phone),
    email = COALESCE($8::text, email),
    status = COALESCE($9::text, status),
    is_active = COALESCE($10::boolean, is_active),
    notes = COALESCE($11::text, notes)
WHERE id = $12
RETURNING id, business_entity_id, code, name, display_name, country, city, address_text, phone, email, status, is_active, notes, created_at, updated_at
`

type UpdateBranchParams struct {
	Code        pgtype.Text `json:"code"`
	Name        pgtype.Text `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	Country     pgtype.Text `json:"country"`
	City        pgtype.Text `json:"city"`
	AddressText pgtype.Text `json:"address_text"`
	Phone       pgtype.Text `json:"phone"`
	Email       pgtype.Text `json:"email"`
	Status      pgtype.Text `json:"status"`
	IsActive    pgtype.Bool `json:"is_active"`
	Notes       pgtype.Text `json:"notes"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.Country,
		arg.City,
		arg.AddressText,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.IsActive,
		arg.Notes,
		arg.ID,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.Country,
		&i.City,
		&i.AddressText,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusinessEntity = `-- name: UpdateBusinessEntity :one
UPDATE business_entities SET
    code = COALESCE($1::text, code),
    name = COALESCE($2::text, name),
    display_name = COALESCE($3::text, display_name),
    default_currency = COALESCE($4::text, default_currency),
    country = COALESCE($5::text, country),
    registration_no = COALESCE($6::text, registration_no),
    tax_no = COALESCE($7::text, tax_no),
    status = COALESCE($8::text, status),
    is_active = COALESCE($9::boolean, is_active),
    notes = COALESCE($10::text, notes)
WHERE id = $11
RETURNING id, code, name, display_name, default_currency, country, registration_no, tax_no, status, is_active, notes, created_at, updated_at
`

type UpdateBusinessEntityParams struct {
	Code            pgtype.Text `json:"code"`
	Name            pgtype.Text `json:"name"`
	DisplayName     pgtype.Text `json:"display_name"`
	DefaultCurrency pgtype.Text `json:"default_currency"`
	Country         pgtype.Text `json:"country"`
	RegistrationNo  pgtype.Text `json:"registration_no"`
	TaxNo           pgtype.Text `json:"tax_no"`
	Status          pgtype.Text `json:"status"`
	IsActive        pgtype.Bool `json:"is_active"`
	Notes           pgtype.Text `json:"notes"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBusinessEntity(ctx context.Context, arg UpdateBusinessEntityParams) (BusinessEntity, error) {
	row := q.db.QueryRow(ctx, updateBusinessEntity,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.DefaultCurrency,
		arg.Country,
		arg.RegistrationNo,
		arg.TaxNo,
		arg.Status,
		arg.IsActive,
		arg.Notes,
		arg.ID,
	)
	var i BusinessEntity
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.DefaultCurrency,
		&i.Country,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
