// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyAdjustment = `-- name: ApplyAdjustment :one
UPDATE public.financial_adjustments
SET status = 'applied',
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'approved'
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at
`

func (q *Queries) ApplyAdjustment(ctx context.Context, id pgtype.UUID) (FinancialAdjustment, error) {
	row := q.db.QueryRow(ctx, applyAdjustment, id)
	var i FinancialAdjustment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.AdjustmentType,
		&i.Amount,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.Status,
		&i.Reason,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applyCreditBalance = `-- name: ApplyCreditBalance :one
UPDATE public.credit_balances
SET amount_used = amount_used + $2,
    status = CASE
        WHEN (amount_total - (amount_used + $2)) <= 0 THEN 'exhausted'
        ELSE status
    END,
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'available'
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, origin_payment_id, origin_adjustment_id, currency_code, amount_total, amount_used, amount_remaining, status, reason, created_at, updated_at
`

type ApplyCreditBalanceParams struct {
	ID         pgtype.UUID    `json:"id"`
	AmountUsed pgtype.Numeric `json:"amount_used"`
}

func (q *Queries) ApplyCreditBalance(ctx context.Context, arg ApplyCreditBalanceParams) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, applyCreditBalance, arg.ID, arg.AmountUsed)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.OriginPaymentID,
		&i.OriginAdjustmentID,
		&i.CurrencyCode,
		&i.AmountTotal,
		&i.AmountUsed,
		&i.AmountRemaining,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveAdjustment = `-- name: ApproveAdjustment :one
UPDATE public.financial_adjustments
SET status = 'approved',
    approved_by_user_id = $2,
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'pending'
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at
`

type ApproveAdjustmentParams struct {
	ID               pgtype.UUID `json:"id"`
	ApprovedByUserID pgtype.UUID `json:"approved_by_user_id"`
}

func (q *Queries) ApproveAdjustment(ctx context.Context, arg ApproveAdjustmentParams) (FinancialAdjustment, error) {
	row := q.db.QueryRow(ctx, approveAdjustment, arg.ID, arg.ApprovedByUserID)
	var i FinancialAdjustment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.AdjustmentType,
		&i.Amount,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.Status,
		&i.Reason,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCreditBalances = `-- name: CountCreditBalances :one
SELECT count(*) FROM public.credit_balances
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR party_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountCreditBalancesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountCreditBalances(ctx context.Context, arg CountCreditBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditBalances, arg.BusinessEntityID, arg.PartyID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFinancialAdjustments = `-- name: CountFinancialAdjustments :one
SELECT count(*) FROM public.financial_adjustments
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountFinancialAdjustmentsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountFinancialAdjustments(ctx context.Context, arg CountFinancialAdjustmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFinancialAdjustments, arg.BusinessEntityID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayments = `-- name: CountPayments :one
SELECT count(*) FROM public.payments
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR party_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountPaymentsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountPayments(ctx context.Context, arg CountPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, arg.BusinessEntityID, arg.PartyID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReceivables = `-- name: CountReceivables :one
SELECT count(*) FROM public.receivables
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR party_id = $2::uuid)
  AND ($3::uuid IS NULL OR unit_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR source_module = $5::text)
`

type CountReceivablesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	Status           pgtype.Text `json:"status"`
	SourceModule     pgtype.Text `json:"source_module"`
}

func (q *Queries) CountReceivables(ctx context.Context, arg CountReceivablesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReceivables,
		arg.BusinessEntityID,
		arg.PartyID,
		arg.UnitID,
		arg.Status,
		arg.SourceModule,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCreditBalance = `-- name: CreateCreditBalance :one
INSERT INTO public.credit_balances (
    business_entity_id, branch_id, party_id,
    source_module, source_record_type, source_record_id,
    origin_payment_id, origin_adjustment_id,
    currency_code, amount_total, reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, origin_payment_id, origin_adjustment_id, currency_code, amount_total, amount_used, amount_remaining, status, reason, created_at, updated_at
`

type CreateCreditBalanceParams struct {
	BusinessEntityID   pgtype.UUID    `json:"business_entity_id"`
	BranchID           pgtype.UUID    `json:"branch_id"`
	PartyID            pgtype.UUID    `json:"party_id"`
	SourceModule       pgtype.Text    `json:"source_module"`
	SourceRecordType   pgtype.Text    `json:"source_record_type"`
	SourceRecordID     pgtype.UUID    `json:"source_record_id"`
	OriginPaymentID    pgtype.UUID    `json:"origin_payment_id"`
	OriginAdjustmentID pgtype.UUID    `json:"origin_adjustment_id"`
	CurrencyCode       string         `json:"currency_code"`
	AmountTotal        pgtype.Numeric `json:"amount_total"`
	Reason             string         `json:"reason"`
}

func (q *Queries) CreateCreditBalance(ctx context.Context, arg CreateCreditBalanceParams) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, createCreditBalance,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.PartyID,
		arg.SourceModule,
		arg.SourceRecordType,
		arg.SourceRecordID,
		arg.OriginPaymentID,
		arg.OriginAdjustmentID,
		arg.CurrencyCode,
		arg.AmountTotal,
		arg.Reason,
	)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.OriginPaymentID,
		&i.OriginAdjustmentID,
		&i.CurrencyCode,
		&i.AmountTotal,
		&i.AmountUsed,
		&i.AmountRemaining,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFinancialAdjustment = `-- name: CreateFinancialAdjustment :one
INSERT INTO public.financial_adjustments (
    business_entity_id, branch_id, party_id,
    source_module, source_record_type, source_record_id,
    adjustment_type, amount, currency_code,
    effective_date, reason, requested_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at
`

type CreateFinancialAdjustmentParams struct {
	BusinessEntityID  pgtype.UUID    `json:"business_entity_id"`
	BranchID          pgtype.UUID    `json:"branch_id"`
	PartyID           pgtype.UUID    `json:"party_id"`
	SourceModule      string         `json:"source_module"`
	SourceRecordType  string         `json:"source_record_type"`
	SourceRecordID    pgtype.UUID    `json:"source_record_id"`
	AdjustmentType    string         `json:"adjustment_type"`
	Amount            pgtype.Numeric `json:"amount"`
	CurrencyCode      string         `json:"currency_code"`
	EffectiveDate     pgtype.Date    `json:"effective_date"`
	Reason            string         `json:"reason"`
	RequestedByUserID pgtype.UUID    `json:"requested_by_user_id"`
}

func (q *Queries) CreateFinancialAdjustment(ctx context.Context, arg CreateFinancialAdjustmentParams) (FinancialAdjustment, error) {
	row := q.db.QueryRow(ctx, createFinancialAdjustment,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.PartyID,
		arg.SourceModule,
		arg.SourceRecordType,
		arg.SourceRecordID,
		arg.AdjustmentType,
		arg.Amount,
		arg.CurrencyCode,
		arg.EffectiveDate,
		arg.Reason,
		arg.RequestedByUserID,
	)
	var i FinancialAdjustment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.AdjustmentType,
		&i.Amount,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.Status,
		&i.Reason,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO public.payments (
    business_entity_id, branch_id, party_id,
    payment_no, receipt_no, payment_date, payment_method,
    currency_code, amount_received, unapplied_amount,
    reference_no, notes, received_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9, $10, $11, $12)
RETURNING id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at
`

type CreatePaymentParams struct {
	BusinessEntityID pgtype.UUID    `json:"business_entity_id"`
	BranchID         pgtype.UUID    `json:"branch_id"`
	PartyID          pgtype.UUID    `json:"party_id"`
	PaymentNo        string         `json:"payment_no"`
	ReceiptNo        pgtype.Text    `json:"receipt_no"`
	PaymentDate      pgtype.Date    `json:"payment_date"`
	PaymentMethod    string         `json:"payment_method"`
	CurrencyCode     string         `json:"currency_code"`
	AmountReceived   pgtype.Numeric `json:"amount_received"`
	ReferenceNo      pgtype.Text    `json:"reference_no"`
	Notes            pgtype.Text    `json:"notes"`
	ReceivedByUserID pgtype.UUID    `json:"received_by_user_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.PartyID,
		arg.PaymentNo,
		arg.ReceiptNo,
		arg.PaymentDate,
		arg.PaymentMethod,
		arg.CurrencyCode,
		arg.AmountReceived,
		arg.ReferenceNo,
		arg.Notes,
		arg.ReceivedByUserID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.PaymentNo,
		&i.ReceiptNo,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.CurrencyCode,
		&i.AmountReceived,
		&i.UnappliedAmount,
		&i.Status,
		&i.ReferenceNo,
		&i.Notes,
		&i.ReceivedByUserID,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentAllocation = `-- name: CreatePaymentAllocation :one

INSERT INTO public.payment_allocations (
    payment_id, receivable_id, allocated_amount, allocation_date, allocation_order, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, payment_id, receivable_id, allocated_amount, allocation_date, allocation_order, notes, created_at
`

type CreatePaymentAllocationParams struct {
	PaymentID       pgtype.UUID    `json:"payment_id"`
	ReceivableID    pgtype.UUID    `json:"receivable_id"`
	AllocatedAmount pgtype.Numeric `json:"allocated_amount"`
	AllocationDate  pgtype.Date    `json:"allocation_date"`
	AllocationOrder int16          `json:"allocation_order"`
	Notes           pgtype.Text    `json:"notes"`
}

// =============================================================================
// Payment Allocations
// =============================================================================
func (q *Queries) CreatePaymentAllocation(ctx context.Context, arg CreatePaymentAllocationParams) (PaymentAllocation, error) {
	row := q.db.QueryRow(ctx, createPaymentAllocation,
		arg.PaymentID,
		arg.ReceivableID,
		arg.AllocatedAmount,
		arg.AllocationDate,
		arg.AllocationOrder,
		arg.Notes,
	)
	var i PaymentAllocation
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.ReceivableID,
		&i.AllocatedAmount,
		&i.AllocationDate,
		&i.AllocationOrder,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createReceivable = `-- name: CreateReceivable :one
INSERT INTO public.receivables (
    business_entity_id, branch_id, party_id, unit_id,
    source_module, source_record_type, source_record_id,
    receivable_no, receivable_date, due_date,
    currency_code, original_amount, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at
`

type CreateReceivableParams struct {
	BusinessEntityID pgtype.UUID    `json:"business_entity_id"`
	BranchID         pgtype.UUID    `json:"branch_id"`
	PartyID          pgtype.UUID    `json:"party_id"`
	UnitID           pgtype.UUID    `json:"unit_id"`
	SourceModule     string         `json:"source_module"`
	SourceRecordType string         `json:"source_record_type"`
	SourceRecordID   pgtype.UUID    `json:"source_record_id"`
	ReceivableNo     pgtype.Text    `json:"receivable_no"`
	ReceivableDate   pgtype.Date    `json:"receivable_date"`
	DueDate          pgtype.Date    `json:"due_date"`
	CurrencyCode     string         `json:"currency_code"`
	OriginalAmount   pgtype.Numeric `json:"original_amount"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateReceivable(ctx context.Context, arg CreateReceivableParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, createReceivable,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.PartyID,
		arg.UnitID,
		arg.SourceModule,
		arg.SourceRecordType,
		arg.SourceRecordID,
		arg.ReceivableNo,
		arg.ReceivableDate,
		arg.DueDate,
		arg.CurrencyCode,
		arg.OriginalAmount,
		arg.Notes,
	)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditBalance = `-- name: GetCreditBalance :one
SELECT id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, origin_payment_id, origin_adjustment_id, currency_code, amount_total, amount_used, amount_remaining, status, reason, created_at, updated_at FROM public.credit_balances WHERE id = $1
`

func (q *Queries) GetCreditBalance(ctx context.Context, id pgtype.UUID) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, getCreditBalance, id)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.OriginPaymentID,
		&i.OriginAdjustmentID,
		&i.CurrencyCode,
		&i.AmountTotal,
		&i.AmountUsed,
		&i.AmountRemaining,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinancialAdjustment = `-- name: GetFinancialAdjustment :one
SELECT id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at FROM public.financial_adjustments WHERE id = $1
`

func (q *Queries) GetFinancialAdjustment(ctx context.Context, id pgtype.UUID) (FinancialAdjustment, error) {
	row := q.db.QueryRow(ctx, getFinancialAdjustment, id)
	var i FinancialAdjustment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.AdjustmentType,
		&i.Amount,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.Status,
		&i.Reason,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyStatement = `-- name: GetPartyStatement :many

SELECT id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at FROM public.receivables
WHERE party_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY due_date ASC
`

type GetPartyStatementParams struct {
	PartyID pgtype.UUID `json:"party_id"`
	Status  pgtype.Text `json:"status"`
}

// =============================================================================
// Statement Queries
// =============================================================================
func (q *Queries) GetPartyStatement(ctx context.Context, arg GetPartyStatementParams) ([]Receivable, error) {
	rows, err := q.db.Query(ctx, getPartyStatement, arg.PartyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receivable{}
	for rows.Next() {
		var i Receivable
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.UnitID,
			&i.SourceModule,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.ReceivableNo,
			&i.ReceivableDate,
			&i.DueDate,
			&i.CurrencyCode,
			&i.OriginalAmount,
			&i.AdjustedAmount,
			&i.PaidAmount,
			&i.CreditedAmount,
			&i.OutstandingAmount,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayment = `-- name: GetPayment :one
SELECT id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at FROM public.payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.PaymentNo,
		&i.ReceiptNo,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.CurrencyCode,
		&i.AmountReceived,
		&i.UnappliedAmount,
		&i.Status,
		&i.ReferenceNo,
		&i.Notes,
		&i.ReceivedByUserID,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceivable = `-- name: GetReceivable :one
SELECT id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at FROM public.receivables WHERE id = $1
`

func (q *Queries) GetReceivable(ctx context.Context, id pgtype.UUID) (Receivable, error) {
	row := q.db.QueryRow(ctx, getReceivable, id)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitStatement = `-- name: GetUnitStatement :many
SELECT id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at FROM public.receivables
WHERE unit_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY due_date ASC
`

type GetUnitStatementParams struct {
	UnitID pgtype.UUID `json:"unit_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) GetUnitStatement(ctx context.Context, arg GetUnitStatementParams) ([]Receivable, error) {
	rows, err := q.db.Query(ctx, getUnitStatement, arg.UnitID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receivable{}
	for rows.Next() {
		var i Receivable
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.UnitID,
			&i.SourceModule,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.ReceivableNo,
			&i.ReceivableDate,
			&i.DueDate,
			&i.CurrencyCode,
			&i.OriginalAmount,
			&i.AdjustedAmount,
			&i.PaidAmount,
			&i.CreditedAmount,
			&i.OutstandingAmount,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsForPayment = `-- name: ListAllocationsForPayment :many
SELECT id, payment_id, receivable_id, allocated_amount, allocation_date, allocation_order, notes, created_at FROM public.payment_allocations
WHERE payment_id = $1
ORDER BY allocation_order ASC
`

func (q *Queries) ListAllocationsForPayment(ctx context.Context, paymentID pgtype.UUID) ([]PaymentAllocation, error) {
	rows, err := q.db.Query(ctx, listAllocationsForPayment, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAllocation{}
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReceivableID,
			&i.AllocatedAmount,
			&i.AllocationDate,
			&i.AllocationOrder,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllocationsForReceivable = `-- name: ListAllocationsForReceivable :many
SELECT id, payment_id, receivable_id, allocated_amount, allocation_date, allocation_order, notes, created_at FROM public.payment_allocations
WHERE receivable_id = $1
ORDER BY allocation_date ASC
`

func (q *Queries) ListAllocationsForReceivable(ctx context.Context, receivableID pgtype.UUID) ([]PaymentAllocation, error) {
	rows, err := q.db.Query(ctx, listAllocationsForReceivable, receivableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentAllocation{}
	for rows.Next() {
		var i PaymentAllocation
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ReceivableID,
			&i.AllocatedAmount,
			&i.AllocationDate,
			&i.AllocationOrder,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditBalances = `-- name: ListCreditBalances :many

SELECT id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, origin_payment_id, origin_adjustment_id, currency_code, amount_total, amount_used, amount_remaining, status, reason, created_at, updated_at FROM public.credit_balances
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::uuid IS NULL OR party_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCreditBalancesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	Status           pgtype.Text `json:"status"`
}

// =============================================================================
// Credit Balances
// =============================================================================
func (q *Queries) ListCreditBalances(ctx context.Context, arg ListCreditBalancesParams) ([]CreditBalance, error) {
	rows, err := q.db.Query(ctx, listCreditBalances,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.PartyID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreditBalance{}
	for rows.Next() {
		var i CreditBalance
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.SourceModule,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.OriginPaymentID,
			&i.OriginAdjustmentID,
			&i.CurrencyCode,
			&i.AmountTotal,
			&i.AmountUsed,
			&i.AmountRemaining,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinancialAdjustments = `-- name: ListFinancialAdjustments :many

SELECT id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at FROM public.financial_adjustments
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFinancialAdjustmentsParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	Status           pgtype.Text `json:"status"`
}

// =============================================================================
// Financial Adjustments
// =============================================================================
func (q *Queries) ListFinancialAdjustments(ctx context.Context, arg ListFinancialAdjustmentsParams) ([]FinancialAdjustment, error) {
	rows, err := q.db.Query(ctx, listFinancialAdjustments,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinancialAdjustment{}
	for rows.Next() {
		var i FinancialAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.SourceModule,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.AdjustmentType,
			&i.Amount,
			&i.CurrencyCode,
			&i.EffectiveDate,
			&i.Status,
			&i.Reason,
			&i.RequestedByUserID,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many

SELECT id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at FROM public.payments
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::uuid IS NULL OR party_id = $4::uuid)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY payment_date DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPaymentsParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	Status           pgtype.Text `json:"status"`
}

// =============================================================================
// Payments
// =============================================================================
func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.PartyID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.PaymentNo,
			&i.ReceiptNo,
			&i.PaymentDate,
			&i.PaymentMethod,
			&i.CurrencyCode,
			&i.AmountReceived,
			&i.UnappliedAmount,
			&i.Status,
			&i.ReferenceNo,
			&i.Notes,
			&i.ReceivedByUserID,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivables = `-- name: ListReceivables :many



SELECT id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at FROM public.receivables
WHERE ($3::uuid IS NULL OR business_entity_id = $3::uuid)
  AND ($4::uuid IS NULL OR party_id = $4::uuid)
  AND ($5::uuid IS NULL OR unit_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
  AND ($7::text IS NULL OR source_module = $7::text)
ORDER BY due_date ASC
LIMIT $1 OFFSET $2
`

type ListReceivablesParams struct {
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PartyID          pgtype.UUID `json:"party_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	Status           pgtype.Text `json:"status"`
	SourceModule     pgtype.Text `json:"source_module"`
}

// backend/db/queries/finance.sql
// =============================================================================
// Shared Finance Domain Queries
// =============================================================================
// =============================================================================
// Receivables
// =============================================================================
func (q *Queries) ListReceivables(ctx context.Context, arg ListReceivablesParams) ([]Receivable, error) {
	rows, err := q.db.Query(ctx, listReceivables,
		arg.Limit,
		arg.Offset,
		arg.BusinessEntityID,
		arg.PartyID,
		arg.UnitID,
		arg.Status,
		arg.SourceModule,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receivable{}
	for rows.Next() {
		var i Receivable
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.PartyID,
			&i.UnitID,
			&i.SourceModule,
			&i.SourceRecordType,
			&i.SourceRecordID,
			&i.ReceivableNo,
			&i.ReceivableDate,
			&i.DueDate,
			&i.CurrencyCode,
			&i.OriginalAmount,
			&i.AdjustedAmount,
			&i.PaidAmount,
			&i.CreditedAmount,
			&i.OutstandingAmount,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postPayment = `-- name: PostPayment :one
UPDATE public.payments
SET status = 'posted',
    posted_at = timezone('utc', now()),
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'draft'
RETURNING id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at
`

func (q *Queries) PostPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, postPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.PaymentNo,
		&i.ReceiptNo,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.CurrencyCode,
		&i.AmountReceived,
		&i.UnappliedAmount,
		&i.Status,
		&i.ReferenceNo,
		&i.Notes,
		&i.ReceivedByUserID,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectAdjustment = `-- name: RejectAdjustment :one
UPDATE public.financial_adjustments
SET status = 'rejected',
    approved_by_user_id = $2,
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'pending'
RETURNING id, business_entity_id, branch_id, party_id, source_module, source_record_type, source_record_id, adjustment_type, amount, currency_code, effective_date, status, reason, requested_by_user_id, approved_by_user_id, created_at, updated_at
`

type RejectAdjustmentParams struct {
	ID               pgtype.UUID `json:"id"`
	ApprovedByUserID pgtype.UUID `json:"approved_by_user_id"`
}

func (q *Queries) RejectAdjustment(ctx context.Context, arg RejectAdjustmentParams) (FinancialAdjustment, error) {
	row := q.db.QueryRow(ctx, rejectAdjustment, arg.ID, arg.ApprovedByUserID)
	var i FinancialAdjustment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.AdjustmentType,
		&i.Amount,
		&i.CurrencyCode,
		&i.EffectiveDate,
		&i.Status,
		&i.Reason,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentUnapplied = `-- name: UpdatePaymentUnapplied :one
UPDATE public.payments
SET unapplied_amount = unapplied_amount - $2,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at
`

type UpdatePaymentUnappliedParams struct {
	ID              pgtype.UUID    `json:"id"`
	UnappliedAmount pgtype.Numeric `json:"unapplied_amount"`
}

func (q *Queries) UpdatePaymentUnapplied(ctx context.Context, arg UpdatePaymentUnappliedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentUnapplied, arg.ID, arg.UnappliedAmount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.PaymentNo,
		&i.ReceiptNo,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.CurrencyCode,
		&i.AmountReceived,
		&i.UnappliedAmount,
		&i.Status,
		&i.ReferenceNo,
		&i.Notes,
		&i.ReceivedByUserID,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceivableAdjustedAmount = `-- name: UpdateReceivableAdjustedAmount :one
UPDATE public.receivables
SET adjusted_amount = adjusted_amount + $2,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at
`

type UpdateReceivableAdjustedAmountParams struct {
	ID             pgtype.UUID    `json:"id"`
	AdjustedAmount pgtype.Numeric `json:"adjusted_amount"`
}

func (q *Queries) UpdateReceivableAdjustedAmount(ctx context.Context, arg UpdateReceivableAdjustedAmountParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, updateReceivableAdjustedAmount, arg.ID, arg.AdjustedAmount)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceivableCreditedAmount = `-- name: UpdateReceivableCreditedAmount :one
UPDATE public.receivables
SET credited_amount = credited_amount + $2,
    status = CASE
        WHEN (original_amount + adjusted_amount - paid_amount - (credited_amount + $2)) <= 0 THEN 'paid'
        WHEN (credited_amount + $2) > 0 OR paid_amount > 0 THEN 'partially_paid'
        ELSE status
    END,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at
`

type UpdateReceivableCreditedAmountParams struct {
	ID             pgtype.UUID    `json:"id"`
	CreditedAmount pgtype.Numeric `json:"credited_amount"`
}

func (q *Queries) UpdateReceivableCreditedAmount(ctx context.Context, arg UpdateReceivableCreditedAmountParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, updateReceivableCreditedAmount, arg.ID, arg.CreditedAmount)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceivablePaidAmount = `-- name: UpdateReceivablePaidAmount :one
UPDATE public.receivables
SET paid_amount = paid_amount + $2,
    status = CASE
        WHEN (original_amount + adjusted_amount - (paid_amount + $2) - credited_amount) <= 0 THEN 'paid'
        WHEN (paid_amount + $2) > 0 THEN 'partially_paid'
        WHEN credited_amount > 0 THEN 'partially_paid'
        ELSE 'open'
    END,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at
`

type UpdateReceivablePaidAmountParams struct {
	ID         pgtype.UUID    `json:"id"`
	PaidAmount pgtype.Numeric `json:"paid_amount"`
}

func (q *Queries) UpdateReceivablePaidAmount(ctx context.Context, arg UpdateReceivablePaidAmountParams) (Receivable, error) {
	row := q.db.QueryRow(ctx, updateReceivablePaidAmount, arg.ID, arg.PaidAmount)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidPayment = `-- name: VoidPayment :one
UPDATE public.payments
SET status = 'voided',
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'posted'
RETURNING id, business_entity_id, branch_id, party_id, payment_no, receipt_no, payment_date, payment_method, currency_code, amount_received, unapplied_amount, status, reference_no, notes, received_by_user_id, posted_at, created_at, updated_at
`

func (q *Queries) VoidPayment(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, voidPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.PaymentNo,
		&i.ReceiptNo,
		&i.PaymentDate,
		&i.PaymentMethod,
		&i.CurrencyCode,
		&i.AmountReceived,
		&i.UnappliedAmount,
		&i.Status,
		&i.ReferenceNo,
		&i.Notes,
		&i.ReceivedByUserID,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidReceivable = `-- name: VoidReceivable :one
UPDATE public.receivables
SET status = 'voided',
    updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'open'
RETURNING id, business_entity_id, branch_id, party_id, unit_id, source_module, source_record_type, source_record_id, receivable_no, receivable_date, due_date, currency_code, original_amount, adjusted_amount, paid_amount, credited_amount, outstanding_amount, status, notes, created_at, updated_at
`

func (q *Queries) VoidReceivable(ctx context.Context, id pgtype.UUID) (Receivable, error) {
	row := q.db.QueryRow(ctx, voidReceivable, id)
	var i Receivable
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.PartyID,
		&i.UnitID,
		&i.SourceModule,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.ReceivableNo,
		&i.ReceivableDate,
		&i.DueDate,
		&i.CurrencyCode,
		&i.OriginalAmount,
		&i.AdjustedAmount,
		&i.PaidAmount,
		&i.CreditedAmount,
		&i.OutstandingAmount,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
