// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)::bigint FROM public.projects
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountProjectsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	IsActive         pgtype.Bool `json:"is_active"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.BusinessEntityID, arg.IsActive, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStructureNodes = `-- name: CountStructureNodes :one
SELECT COUNT(*)::bigint FROM public.structure_nodes
WHERE project_id = $1::uuid
  AND ($2::uuid IS NULL OR parent_structure_node_id = $2::uuid)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
  AND ($4::text IS NULL OR status = $4::text)
`

type CountStructureNodesParams struct {
	ProjectID             pgtype.UUID `json:"project_id"`
	ParentStructureNodeID pgtype.UUID `json:"parent_structure_node_id"`
	IsActive              pgtype.Bool `json:"is_active"`
	Status                pgtype.Text `json:"status"`
}

func (q *Queries) CountStructureNodes(ctx context.Context, arg CountStructureNodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStructureNodes,
		arg.ProjectID,
		arg.ParentStructureNodeID,
		arg.IsActive,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnits = `-- name: CountUnits :one
SELECT COUNT(*)::bigint FROM public.units
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::uuid IS NULL OR structure_node_id = $3::uuid)
  AND ($4::text IS NULL OR inventory_status = $4::text)
  AND ($5::text IS NULL OR sales_status = $5::text)
  AND ($6::boolean IS NULL OR is_active = $6::boolean)
`

type CountUnitsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	StructureNodeID  pgtype.UUID `json:"structure_node_id"`
	InventoryStatus  pgtype.Text `json:"inventory_status"`
	SalesStatus      pgtype.Text `json:"sales_status"`
	IsActive         pgtype.Bool `json:"is_active"`
}

func (q *Queries) CountUnits(ctx context.Context, arg CountUnitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnits,
		arg.BusinessEntityID,
		arg.ProjectID,
		arg.StructureNodeID,
		arg.InventoryStatus,
		arg.SalesStatus,
		arg.IsActive,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO public.projects (
    business_entity_id,
    primary_branch_id,
    code,
    name,
    display_name,
    project_type,
    structure_type,
    status,
    country,
    city,
    district_area,
    address_text,
    default_currency,
    launch_date,
    handover_date,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, business_entity_id, primary_branch_id, code, name, display_name, project_type, structure_type, status, country, city, district_area, address_text, default_currency, launch_date, handover_date, notes, is_active, created_at, updated_at
`

type CreateProjectParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PrimaryBranchID  pgtype.UUID `json:"primary_branch_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	DisplayName      pgtype.Text `json:"display_name"`
	ProjectType      string      `json:"project_type"`
	StructureType    string      `json:"structure_type"`
	Status           string      `json:"status"`
	Country          string      `json:"country"`
	City             pgtype.Text `json:"city"`
	DistrictArea     pgtype.Text `json:"district_area"`
	AddressText      pgtype.Text `json:"address_text"`
	DefaultCurrency  string      `json:"default_currency"`
	LaunchDate       pgtype.Date `json:"launch_date"`
	HandoverDate     pgtype.Date `json:"handover_date"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.BusinessEntityID,
		arg.PrimaryBranchID,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.ProjectType,
		arg.StructureType,
		arg.Status,
		arg.Country,
		arg.City,
		arg.DistrictArea,
		arg.AddressText,
		arg.DefaultCurrency,
		arg.LaunchDate,
		arg.HandoverDate,
		arg.Notes,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.PrimaryBranchID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.ProjectType,
		&i.StructureType,
		&i.Status,
		&i.Country,
		&i.City,
		&i.DistrictArea,
		&i.AddressText,
		&i.DefaultCurrency,
		&i.LaunchDate,
		&i.HandoverDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStructureNode = `-- name: CreateStructureNode :one
INSERT INTO public.structure_nodes (
    project_id,
    parent_structure_node_id,
    node_type,
    code,
    name,
    display_order,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, project_id, parent_structure_node_id, node_type, code, name, display_order, status, is_active, notes, created_at, updated_at
`

type CreateStructureNodeParams struct {
	ProjectID             pgtype.UUID `json:"project_id"`
	ParentStructureNodeID pgtype.UUID `json:"parent_structure_node_id"`
	NodeType              string      `json:"node_type"`
	Code                  string      `json:"code"`
	Name                  string      `json:"name"`
	DisplayOrder          int32       `json:"display_order"`
	Status                string      `json:"status"`
	Notes                 pgtype.Text `json:"notes"`
}

func (q *Queries) CreateStructureNode(ctx context.Context, arg CreateStructureNodeParams) (StructureNode, error) {
	row := q.db.QueryRow(ctx, createStructureNode,
		arg.ProjectID,
		arg.ParentStructureNodeID,
		arg.NodeType,
		arg.Code,
		arg.Name,
		arg.DisplayOrder,
		arg.Status,
		arg.Notes,
	)
	var i StructureNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentStructureNodeID,
		&i.NodeType,
		&i.Code,
		&i.Name,
		&i.DisplayOrder,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO public.units (
    business_entity_id,
    branch_id,
    project_id,
    structure_node_id,
    parent_unit_id,
    unit_type,
    commercial_disposition,
    unit_code,
    display_code,
    unit_no,
    floor_value,
    floor_sort_value,
    section_no,
    entrance_no,
    bedroom_count,
    bathroom_count,
    area_gross_sqm,
    area_net_sqm,
    area_chargeable_sqm,
    land_area_sqm,
    facing_direction,
    inventory_status,
    sales_status,
    occupancy_status,
    maintenance_status,
    list_price_amount,
    list_price_currency,
    valuation_amount,
    metadata_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29
) RETURNING id, business_entity_id, branch_id, project_id, structure_node_id, parent_unit_id, unit_type, commercial_disposition, unit_code, display_code, unit_no, floor_value, floor_sort_value, section_no, entrance_no, bedroom_count, bathroom_count, area_gross_sqm, area_net_sqm, area_chargeable_sqm, land_area_sqm, facing_direction, inventory_status, sales_status, occupancy_status, maintenance_status, list_price_amount, list_price_currency, valuation_amount, is_active, metadata_json, created_at, updated_at
`

type CreateUnitParams struct {
	BusinessEntityID      pgtype.UUID    `json:"business_entity_id"`
	BranchID              pgtype.UUID    `json:"branch_id"`
	ProjectID             pgtype.UUID    `json:"project_id"`
	StructureNodeID       pgtype.UUID    `json:"structure_node_id"`
	ParentUnitID          pgtype.UUID    `json:"parent_unit_id"`
	UnitType              string         `json:"unit_type"`
	CommercialDisposition string         `json:"commercial_disposition"`
	UnitCode              string         `json:"unit_code"`
	DisplayCode           pgtype.Text    `json:"display_code"`
	UnitNo                pgtype.Text    `json:"unit_no"`
	FloorValue            pgtype.Text    `json:"floor_value"`
	FloorSortValue        pgtype.Int4    `json:"floor_sort_value"`
	SectionNo             pgtype.Text    `json:"section_no"`
	EntranceNo            pgtype.Text    `json:"entrance_no"`
	BedroomCount          pgtype.Int2    `json:"bedroom_count"`
	BathroomCount         pgtype.Int2    `json:"bathroom_count"`
	AreaGrossSqm          pgtype.Numeric `json:"area_gross_sqm"`
	AreaNetSqm            pgtype.Numeric `json:"area_net_sqm"`
	AreaChargeableSqm     pgtype.Numeric `json:"area_chargeable_sqm"`
	LandAreaSqm           pgtype.Numeric `json:"land_area_sqm"`
	FacingDirection       pgtype.Text    `json:"facing_direction"`
	InventoryStatus       string         `json:"inventory_status"`
	SalesStatus           string         `json:"sales_status"`
	OccupancyStatus       string         `json:"occupancy_status"`
	MaintenanceStatus     string         `json:"maintenance_status"`
	ListPriceAmount       pgtype.Numeric `json:"list_price_amount"`
	ListPriceCurrency     string         `json:"list_price_currency"`
	ValuationAmount       pgtype.Numeric `json:"valuation_amount"`
	MetadataJson          []byte         `json:"metadata_json"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.StructureNodeID,
		arg.ParentUnitID,
		arg.UnitType,
		arg.CommercialDisposition,
		arg.UnitCode,
		arg.DisplayCode,
		arg.UnitNo,
		arg.FloorValue,
		arg.FloorSortValue,
		arg.SectionNo,
		arg.EntranceNo,
		arg.BedroomCount,
		arg.BathroomCount,
		arg.AreaGrossSqm,
		arg.AreaNetSqm,
		arg.AreaChargeableSqm,
		arg.LandAreaSqm,
		arg.FacingDirection,
		arg.InventoryStatus,
		arg.SalesStatus,
		arg.OccupancyStatus,
		arg.MaintenanceStatus,
		arg.ListPriceAmount,
		arg.ListPriceCurrency,
		arg.ValuationAmount,
		arg.MetadataJson,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.StructureNodeID,
		&i.ParentUnitID,
		&i.UnitType,
		&i.CommercialDisposition,
		&i.UnitCode,
		&i.DisplayCode,
		&i.UnitNo,
		&i.FloorValue,
		&i.FloorSortValue,
		&i.SectionNo,
		&i.EntranceNo,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.AreaGrossSqm,
		&i.AreaNetSqm,
		&i.AreaChargeableSqm,
		&i.LandAreaSqm,
		&i.FacingDirection,
		&i.InventoryStatus,
		&i.SalesStatus,
		&i.OccupancyStatus,
		&i.MaintenanceStatus,
		&i.ListPriceAmount,
		&i.ListPriceCurrency,
		&i.ValuationAmount,
		&i.IsActive,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProject = `-- name: DeactivateProject :exec
UPDATE public.projects SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProject, id)
	return err
}

const deactivateStructureNode = `-- name: DeactivateStructureNode :exec
UPDATE public.structure_nodes SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateStructureNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateStructureNode, id)
	return err
}

const deactivateUnit = `-- name: DeactivateUnit :exec
UPDATE public.units SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateUnit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUnit, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, business_entity_id, primary_branch_id, code, name, display_name, project_type, structure_type, status, country, city, district_area, address_text, default_currency, launch_date, handover_date, notes, is_active, created_at, updated_at FROM public.projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.PrimaryBranchID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.ProjectType,
		&i.StructureType,
		&i.Status,
		&i.Country,
		&i.City,
		&i.DistrictArea,
		&i.AddressText,
		&i.DefaultCurrency,
		&i.LaunchDate,
		&i.HandoverDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStructureNode = `-- name: GetStructureNode :one
SELECT id, project_id, parent_structure_node_id, node_type, code, name, display_order, status, is_active, notes, created_at, updated_at FROM public.structure_nodes WHERE id = $1
`

func (q *Queries) GetStructureNode(ctx context.Context, id pgtype.UUID) (StructureNode, error) {
	row := q.db.QueryRow(ctx, getStructureNode, id)
	var i StructureNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentStructureNodeID,
		&i.NodeType,
		&i.Code,
		&i.Name,
		&i.DisplayOrder,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, business_entity_id, branch_id, project_id, structure_node_id, parent_unit_id, unit_type, commercial_disposition, unit_code, display_code, unit_no, floor_value, floor_sort_value, section_no, entrance_no, bedroom_count, bathroom_count, area_gross_sqm, area_net_sqm, area_chargeable_sqm, land_area_sqm, facing_direction, inventory_status, sales_status, occupancy_status, maintenance_status, list_price_amount, list_price_currency, valuation_amount, is_active, metadata_json, created_at, updated_at FROM public.units WHERE id = $1
`

func (q *Queries) GetUnit(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.StructureNodeID,
		&i.ParentUnitID,
		&i.UnitType,
		&i.CommercialDisposition,
		&i.UnitCode,
		&i.DisplayCode,
		&i.UnitNo,
		&i.FloorValue,
		&i.FloorSortValue,
		&i.SectionNo,
		&i.EntranceNo,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.AreaGrossSqm,
		&i.AreaNetSqm,
		&i.AreaChargeableSqm,
		&i.LandAreaSqm,
		&i.FacingDirection,
		&i.InventoryStatus,
		&i.SalesStatus,
		&i.OccupancyStatus,
		&i.MaintenanceStatus,
		&i.ListPriceAmount,
		&i.ListPriceCurrency,
		&i.ValuationAmount,
		&i.IsActive,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many


SELECT id, business_entity_id, primary_branch_id, code, name, display_name, project_type, structure_type, status, country, city, district_area, address_text, default_currency, launch_date, handover_date, notes, is_active, created_at, updated_at FROM public.projects
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::boolean IS NULL OR is_active = $2::boolean)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY name ASC
LIMIT $5::int OFFSET $4::int
`

type ListProjectsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	IsActive         pgtype.Bool `json:"is_active"`
	Status           pgtype.Text `json:"status"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// =============================================================================
// Inventory Domain Queries
// =============================================================================
// =============================================================================
// Projects
// =============================================================================
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.BusinessEntityID,
		arg.IsActive,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.PrimaryBranchID,
			&i.Code,
			&i.Name,
			&i.DisplayName,
			&i.ProjectType,
			&i.StructureType,
			&i.Status,
			&i.Country,
			&i.City,
			&i.DistrictArea,
			&i.AddressText,
			&i.DefaultCurrency,
			&i.LaunchDate,
			&i.HandoverDate,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureNodes = `-- name: ListStructureNodes :many

SELECT id, project_id, parent_structure_node_id, node_type, code, name, display_order, status, is_active, notes, created_at, updated_at FROM public.structure_nodes
WHERE project_id = $1::uuid
  AND ($2::uuid IS NULL OR parent_structure_node_id = $2::uuid)
  AND ($3::boolean IS NULL OR is_active = $3::boolean)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY display_order ASC, code ASC
LIMIT $6::int OFFSET $5::int
`

type ListStructureNodesParams struct {
	ProjectID             pgtype.UUID `json:"project_id"`
	ParentStructureNodeID pgtype.UUID `json:"parent_structure_node_id"`
	IsActive              pgtype.Bool `json:"is_active"`
	Status                pgtype.Text `json:"status"`
	Offset                int32       `json:"offset"`
	Limit                 int32       `json:"limit"`
}

// =============================================================================
// Structure Nodes
// =============================================================================
func (q *Queries) ListStructureNodes(ctx context.Context, arg ListStructureNodesParams) ([]StructureNode, error) {
	rows, err := q.db.Query(ctx, listStructureNodes,
		arg.ProjectID,
		arg.ParentStructureNodeID,
		arg.IsActive,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StructureNode{}
	for rows.Next() {
		var i StructureNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentStructureNodeID,
			&i.NodeType,
			&i.Code,
			&i.Name,
			&i.DisplayOrder,
			&i.Status,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many

SELECT id, business_entity_id, branch_id, project_id, structure_node_id, parent_unit_id, unit_type, commercial_disposition, unit_code, display_code, unit_no, floor_value, floor_sort_value, section_no, entrance_no, bedroom_count, bathroom_count, area_gross_sqm, area_net_sqm, area_chargeable_sqm, land_area_sqm, facing_direction, inventory_status, sales_status, occupancy_status, maintenance_status, list_price_amount, list_price_currency, valuation_amount, is_active, metadata_json, created_at, updated_at FROM public.units
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::uuid IS NULL OR structure_node_id = $3::uuid)
  AND ($4::text IS NULL OR inventory_status = $4::text)
  AND ($5::text IS NULL OR sales_status = $5::text)
  AND ($6::boolean IS NULL OR is_active = $6::boolean)
ORDER BY unit_code ASC
LIMIT $8::int OFFSET $7::int
`

type ListUnitsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	StructureNodeID  pgtype.UUID `json:"structure_node_id"`
	InventoryStatus  pgtype.Text `json:"inventory_status"`
	SalesStatus      pgtype.Text `json:"sales_status"`
	IsActive         pgtype.Bool `json:"is_active"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// =============================================================================
// Units
// =============================================================================
func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits,
		arg.BusinessEntityID,
		arg.ProjectID,
		arg.StructureNodeID,
		arg.InventoryStatus,
		arg.SalesStatus,
		arg.IsActive,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.ProjectID,
			&i.StructureNodeID,
			&i.ParentUnitID,
			&i.UnitType,
			&i.CommercialDisposition,
			&i.UnitCode,
			&i.DisplayCode,
			&i.UnitNo,
			&i.FloorValue,
			&i.FloorSortValue,
			&i.SectionNo,
			&i.EntranceNo,
			&i.BedroomCount,
			&i.BathroomCount,
			&i.AreaGrossSqm,
			&i.AreaNetSqm,
			&i.AreaChargeableSqm,
			&i.LandAreaSqm,
			&i.FacingDirection,
			&i.InventoryStatus,
			&i.SalesStatus,
			&i.OccupancyStatus,
			&i.MaintenanceStatus,
			&i.ListPriceAmount,
			&i.ListPriceCurrency,
			&i.ValuationAmount,
			&i.IsActive,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE public.projects SET
    primary_branch_id = COALESCE($1::uuid, primary_branch_id),
    code = COALESCE($2::text, code),
    name = COALESCE($3::text, name),
    display_name = COALESCE($4::text, display_name),
    project_type = COALESCE($5::text, project_type),
    structure_type = COALESCE($6::text, structure_type),
    status = COALESCE($7::text, status),
    country = COALESCE($8::text, country),
    city = COALESCE($9::text, city),
    district_area = COALESCE($10::text, district_area),
    address_text = COALESCE($11::text, address_text),
    default_currency = COALESCE($12::text, default_currency),
    launch_date = COALESCE($13::date, launch_date),
    handover_date = COALESCE($14::date, handover_date),
    notes = COALESCE($15::text, notes),
    is_active = COALESCE($16::boolean, is_active)
WHERE id = $17::uuid
RETURNING id, business_entity_id, primary_branch_id, code, name, display_name, project_type, structure_type, status, country, city, district_area, address_text, default_currency, launch_date, handover_date, notes, is_active, created_at, updated_at
`

type UpdateProjectParams struct {
	PrimaryBranchID pgtype.UUID `json:"primary_branch_id"`
	Code            pgtype.Text `json:"code"`
	Name            pgtype.Text `json:"name"`
	DisplayName     pgtype.Text `json:"display_name"`
	ProjectType     pgtype.Text `json:"project_type"`
	StructureType   pgtype.Text `json:"structure_type"`
	Status          pgtype.Text `json:"status"`
	Country         pgtype.Text `json:"country"`
	City            pgtype.Text `json:"city"`
	DistrictArea    pgtype.Text `json:"district_area"`
	AddressText     pgtype.Text `json:"address_text"`
	DefaultCurrency pgtype.Text `json:"default_currency"`
	LaunchDate      pgtype.Date `json:"launch_date"`
	HandoverDate    pgtype.Date `json:"handover_date"`
	Notes           pgtype.Text `json:"notes"`
	IsActive        pgtype.Bool `json:"is_active"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.PrimaryBranchID,
		arg.Code,
		arg.Name,
		arg.DisplayName,
		arg.ProjectType,
		arg.StructureType,
		arg.Status,
		arg.Country,
		arg.City,
		arg.DistrictArea,
		arg.AddressText,
		arg.DefaultCurrency,
		arg.LaunchDate,
		arg.HandoverDate,
		arg.Notes,
		arg.IsActive,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.PrimaryBranchID,
		&i.Code,
		&i.Name,
		&i.DisplayName,
		&i.ProjectType,
		&i.StructureType,
		&i.Status,
		&i.Country,
		&i.City,
		&i.DistrictArea,
		&i.AddressText,
		&i.DefaultCurrency,
		&i.LaunchDate,
		&i.HandoverDate,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStructureNode = `-- name: UpdateStructureNode :one
UPDATE public.structure_nodes SET
    parent_structure_node_id = COALESCE($1::uuid, parent_structure_node_id),
    node_type = COALESCE($2::text, node_type),
    name = COALESCE($3::text, name),
    display_order = COALESCE($4::int, display_order),
    status = COALESCE($5::text, status),
    notes = COALESCE($6::text, notes),
    is_active = COALESCE($7::boolean, is_active)
WHERE id = $8::uuid
RETURNING id, project_id, parent_structure_node_id, node_type, code, name, display_order, status, is_active, notes, created_at, updated_at
`

type UpdateStructureNodeParams struct {
	ParentStructureNodeID pgtype.UUID `json:"parent_structure_node_id"`
	NodeType              pgtype.Text `json:"node_type"`
	Name                  pgtype.Text `json:"name"`
	DisplayOrder          pgtype.Int4 `json:"display_order"`
	Status                pgtype.Text `json:"status"`
	Notes                 pgtype.Text `json:"notes"`
	IsActive              pgtype.Bool `json:"is_active"`
	ID                    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStructureNode(ctx context.Context, arg UpdateStructureNodeParams) (StructureNode, error) {
	row := q.db.QueryRow(ctx, updateStructureNode,
		arg.ParentStructureNodeID,
		arg.NodeType,
		arg.Name,
		arg.DisplayOrder,
		arg.Status,
		arg.Notes,
		arg.IsActive,
		arg.ID,
	)
	var i StructureNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentStructureNodeID,
		&i.NodeType,
		&i.Code,
		&i.Name,
		&i.DisplayOrder,
		&i.Status,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE public.units SET
    structure_node_id = COALESCE($1::uuid, structure_node_id),
    parent_unit_id = COALESCE($2::uuid, parent_unit_id),
    unit_type = COALESCE($3::text, unit_type),
    commercial_disposition = COALESCE($4::text, commercial_disposition),
    display_code = COALESCE($5::text, display_code),
    unit_no = COALESCE($6::text, unit_no),
    floor_value = COALESCE($7::text, floor_value),
    floor_sort_value = COALESCE($8::int, floor_sort_value),
    section_no = COALESCE($9::text, section_no),
    entrance_no = COALESCE($10::text, entrance_no),
    bedroom_count = COALESCE($11::smallint, bedroom_count),
    bathroom_count = COALESCE($12::smallint, bathroom_count),
    area_gross_sqm = COALESCE($13::numeric, area_gross_sqm),
    area_net_sqm = COALESCE($14::numeric, area_net_sqm),
    area_chargeable_sqm = COALESCE($15::numeric, area_chargeable_sqm),
    land_area_sqm = COALESCE($16::numeric, land_area_sqm),
    facing_direction = COALESCE($17::text, facing_direction),
    inventory_status = COALESCE($18::text, inventory_status),
    sales_status = COALESCE($19::text, sales_status),
    occupancy_status = COALESCE($20::text, occupancy_status),
    maintenance_status = COALESCE($21::text, maintenance_status),
    list_price_amount = COALESCE($22::numeric, list_price_amount),
    list_price_currency = COALESCE($23::text, list_price_currency),
    valuation_amount = COALESCE($24::numeric, valuation_amount),
    metadata_json = COALESCE($25::jsonb, metadata_json),
    is_active = COALESCE($26::boolean, is_active)
WHERE id = $27::uuid
RETURNING id, business_entity_id, branch_id, project_id, structure_node_id, parent_unit_id, unit_type, commercial_disposition, unit_code, display_code, unit_no, floor_value, floor_sort_value, section_no, entrance_no, bedroom_count, bathroom_count, area_gross_sqm, area_net_sqm, area_chargeable_sqm, land_area_sqm, facing_direction, inventory_status, sales_status, occupancy_status, maintenance_status, list_price_amount, list_price_currency, valuation_amount, is_active, metadata_json, created_at, updated_at
`

type UpdateUnitParams struct {
	StructureNodeID       pgtype.UUID    `json:"structure_node_id"`
	ParentUnitID          pgtype.UUID    `json:"parent_unit_id"`
	UnitType              pgtype.Text    `json:"unit_type"`
	CommercialDisposition pgtype.Text    `json:"commercial_disposition"`
	DisplayCode           pgtype.Text    `json:"display_code"`
	UnitNo                pgtype.Text    `json:"unit_no"`
	FloorValue            pgtype.Text    `json:"floor_value"`
	FloorSortValue        pgtype.Int4    `json:"floor_sort_value"`
	SectionNo             pgtype.Text    `json:"section_no"`
	EntranceNo            pgtype.Text    `json:"entrance_no"`
	BedroomCount          pgtype.Int2    `json:"bedroom_count"`
	BathroomCount         pgtype.Int2    `json:"bathroom_count"`
	AreaGrossSqm          pgtype.Numeric `json:"area_gross_sqm"`
	AreaNetSqm            pgtype.Numeric `json:"area_net_sqm"`
	AreaChargeableSqm     pgtype.Numeric `json:"area_chargeable_sqm"`
	LandAreaSqm           pgtype.Numeric `json:"land_area_sqm"`
	FacingDirection       pgtype.Text    `json:"facing_direction"`
	InventoryStatus       pgtype.Text    `json:"inventory_status"`
	SalesStatus           pgtype.Text    `json:"sales_status"`
	OccupancyStatus       pgtype.Text    `json:"occupancy_status"`
	MaintenanceStatus     pgtype.Text    `json:"maintenance_status"`
	ListPriceAmount       pgtype.Numeric `json:"list_price_amount"`
	ListPriceCurrency     pgtype.Text    `json:"list_price_currency"`
	ValuationAmount       pgtype.Numeric `json:"valuation_amount"`
	MetadataJson          []byte         `json:"metadata_json"`
	IsActive              pgtype.Bool    `json:"is_active"`
	ID                    pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.StructureNodeID,
		arg.ParentUnitID,
		arg.UnitType,
		arg.CommercialDisposition,
		arg.DisplayCode,
		arg.UnitNo,
		arg.FloorValue,
		arg.FloorSortValue,
		arg.SectionNo,
		arg.EntranceNo,
		arg.BedroomCount,
		arg.BathroomCount,
		arg.AreaGrossSqm,
		arg.AreaNetSqm,
		arg.AreaChargeableSqm,
		arg.LandAreaSqm,
		arg.FacingDirection,
		arg.InventoryStatus,
		arg.SalesStatus,
		arg.OccupancyStatus,
		arg.MaintenanceStatus,
		arg.ListPriceAmount,
		arg.ListPriceCurrency,
		arg.ValuationAmount,
		arg.MetadataJson,
		arg.IsActive,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.StructureNodeID,
		&i.ParentUnitID,
		&i.UnitType,
		&i.CommercialDisposition,
		&i.UnitCode,
		&i.DisplayCode,
		&i.UnitNo,
		&i.FloorValue,
		&i.FloorSortValue,
		&i.SectionNo,
		&i.EntranceNo,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.AreaGrossSqm,
		&i.AreaNetSqm,
		&i.AreaChargeableSqm,
		&i.LandAreaSqm,
		&i.FacingDirection,
		&i.InventoryStatus,
		&i.SalesStatus,
		&i.OccupancyStatus,
		&i.MaintenanceStatus,
		&i.ListPriceAmount,
		&i.ListPriceCurrency,
		&i.ValuationAmount,
		&i.IsActive,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitCode = `-- name: UpdateUnitCode :one
UPDATE public.units SET
    unit_code = $1::text,
    display_code = COALESCE($2::text, display_code)
WHERE id = $3::uuid
RETURNING id, business_entity_id, branch_id, project_id, structure_node_id, parent_unit_id, unit_type, commercial_disposition, unit_code, display_code, unit_no, floor_value, floor_sort_value, section_no, entrance_no, bedroom_count, bathroom_count, area_gross_sqm, area_net_sqm, area_chargeable_sqm, land_area_sqm, facing_direction, inventory_status, sales_status, occupancy_status, maintenance_status, list_price_amount, list_price_currency, valuation_amount, is_active, metadata_json, created_at, updated_at
`

type UpdateUnitCodeParams struct {
	UnitCode    string      `json:"unit_code"`
	DisplayCode pgtype.Text `json:"display_code"`
	ID          pgtype.UUID `json:"id"`
}

// Permission: inventory.unit.edit_code (per technical-specs.md Section 12.2)
func (q *Queries) UpdateUnitCode(ctx context.Context, arg UpdateUnitCodeParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnitCode, arg.UnitCode, arg.DisplayCode, arg.ID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.StructureNodeID,
		&i.ParentUnitID,
		&i.UnitType,
		&i.CommercialDisposition,
		&i.UnitCode,
		&i.DisplayCode,
		&i.UnitNo,
		&i.FloorValue,
		&i.FloorSortValue,
		&i.SectionNo,
		&i.EntranceNo,
		&i.BedroomCount,
		&i.BathroomCount,
		&i.AreaGrossSqm,
		&i.AreaNetSqm,
		&i.AreaChargeableSqm,
		&i.LandAreaSqm,
		&i.FacingDirection,
		&i.InventoryStatus,
		&i.SalesStatus,
		&i.OccupancyStatus,
		&i.MaintenanceStatus,
		&i.ListPriceAmount,
		&i.ListPriceCurrency,
		&i.ValuationAmount,
		&i.IsActive,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitInventoryStatus = `-- name: UpdateUnitInventoryStatus :exec
UPDATE public.units SET inventory_status = $2 WHERE id = $1
`

type UpdateUnitInventoryStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	InventoryStatus string      `json:"inventory_status"`
}

func (q *Queries) UpdateUnitInventoryStatus(ctx context.Context, arg UpdateUnitInventoryStatusParams) error {
	_, err := q.db.Exec(ctx, updateUnitInventoryStatus, arg.ID, arg.InventoryStatus)
	return err
}

const updateUnitOccupancyStatus = `-- name: UpdateUnitOccupancyStatus :exec
UPDATE public.units SET occupancy_status = $2 WHERE id = $1
`

type UpdateUnitOccupancyStatusParams struct {
	ID              pgtype.UUID `json:"id"`
	OccupancyStatus string      `json:"occupancy_status"`
}

func (q *Queries) UpdateUnitOccupancyStatus(ctx context.Context, arg UpdateUnitOccupancyStatusParams) error {
	_, err := q.db.Exec(ctx, updateUnitOccupancyStatus, arg.ID, arg.OccupancyStatus)
	return err
}
