// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalPolicy struct {
	ID                     pgtype.UUID        `json:"id"`
	BusinessEntityID       pgtype.UUID        `json:"business_entity_id"`
	Code                   string             `json:"code"`
	Name                   string             `json:"name"`
	Module                 string             `json:"module"`
	RequestType            string             `json:"request_type"`
	MinApprovers           int16              `json:"min_approvers"`
	PreventSelfApproval    bool               `json:"prevent_self_approval"`
	ApproverRoleID         pgtype.UUID        `json:"approver_role_id"`
	AutoApproveBelowAmount pgtype.Numeric     `json:"auto_approve_below_amount"`
	ExpiryHours            pgtype.Int4        `json:"expiry_hours"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type ApprovalRequest struct {
	ID                  pgtype.UUID        `json:"id"`
	BusinessEntityID    pgtype.UUID        `json:"business_entity_id"`
	BranchID            pgtype.UUID        `json:"branch_id"`
	ApprovalPolicyID    pgtype.UUID        `json:"approval_policy_id"`
	Module              string             `json:"module"`
	RequestType         string             `json:"request_type"`
	SourceRecordType    string             `json:"source_record_type"`
	SourceRecordID      pgtype.UUID        `json:"source_record_id"`
	RequestedByUserID   pgtype.UUID        `json:"requested_by_user_id"`
	AssignedToUserID    pgtype.UUID        `json:"assigned_to_user_id"`
	Status              string             `json:"status"`
	SubmittedAt         pgtype.Timestamptz `json:"submitted_at"`
	DecidedAt           pgtype.Timestamptz `json:"decided_at"`
	DecisionReason      pgtype.Text        `json:"decision_reason"`
	PayloadSnapshotJson []byte             `json:"payload_snapshot_json"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ApprovalRequestApprover struct {
	ID                pgtype.UUID        `json:"id"`
	ApprovalRequestID pgtype.UUID        `json:"approval_request_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Decision          pgtype.Text        `json:"decision"`
	DecidedAt         pgtype.Timestamptz `json:"decided_at"`
	DecisionReason    pgtype.Text        `json:"decision_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID                       pgtype.UUID        `json:"id"`
	EventTime                pgtype.Timestamptz `json:"event_time"`
	UserID                   pgtype.UUID        `json:"user_id"`
	Module                   string             `json:"module"`
	ActionType               string             `json:"action_type"`
	EntityType               string             `json:"entity_type"`
	EntityID                 pgtype.UUID        `json:"entity_id"`
	ScopeType                string             `json:"scope_type"`
	ScopeID                  pgtype.UUID        `json:"scope_id"`
	ResultStatus             string             `json:"result_status"`
	Reason                   pgtype.Text        `json:"reason"`
	SummaryText              string             `json:"summary_text"`
	BeforeSnapshotJson       []byte             `json:"before_snapshot_json"`
	AfterSnapshotJson        []byte             `json:"after_snapshot_json"`
	RelatedApprovalRequestID pgtype.UUID        `json:"related_approval_request_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID               pgtype.UUID        `json:"id"`
	BusinessEntityID pgtype.UUID        `json:"business_entity_id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	DisplayName      pgtype.Text        `json:"display_name"`
	Country          pgtype.Text        `json:"country"`
	City             pgtype.Text        `json:"city"`
	AddressText      pgtype.Text        `json:"address_text"`
	Phone            pgtype.Text        `json:"phone"`
	Email            pgtype.Text        `json:"email"`
	Status           string             `json:"status"`
	IsActive         bool               `json:"is_active"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BusinessEntity struct {
	ID              pgtype.UUID        `json:"id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	DisplayName     pgtype.Text        `json:"display_name"`
	DefaultCurrency string             `json:"default_currency"`
	Country         pgtype.Text        `json:"country"`
	RegistrationNo  pgtype.Text        `json:"registration_no"`
	TaxNo           pgtype.Text        `json:"tax_no"`
	Status          string             `json:"status"`
	IsActive        bool               `json:"is_active"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CreditBalance struct {
	ID                 pgtype.UUID        `json:"id"`
	BusinessEntityID   pgtype.UUID        `json:"business_entity_id"`
	BranchID           pgtype.UUID        `json:"branch_id"`
	PartyID            pgtype.UUID        `json:"party_id"`
	SourceModule       pgtype.Text        `json:"source_module"`
	SourceRecordType   pgtype.Text        `json:"source_record_type"`
	SourceRecordID     pgtype.UUID        `json:"source_record_id"`
	OriginPaymentID    pgtype.UUID        `json:"origin_payment_id"`
	OriginAdjustmentID pgtype.UUID        `json:"origin_adjustment_id"`
	CurrencyCode       string             `json:"currency_code"`
	AmountTotal        pgtype.Numeric     `json:"amount_total"`
	AmountUsed         pgtype.Numeric     `json:"amount_used"`
	AmountRemaining    pgtype.Numeric     `json:"amount_remaining"`
	Status             string             `json:"status"`
	Reason             string             `json:"reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type FinancialAdjustment struct {
	ID                pgtype.UUID        `json:"id"`
	BusinessEntityID  pgtype.UUID        `json:"business_entity_id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	PartyID           pgtype.UUID        `json:"party_id"`
	SourceModule      string             `json:"source_module"`
	SourceRecordType  string             `json:"source_record_type"`
	SourceRecordID    pgtype.UUID        `json:"source_record_id"`
	AdjustmentType    string             `json:"adjustment_type"`
	Amount            pgtype.Numeric     `json:"amount"`
	CurrencyCode      string             `json:"currency_code"`
	EffectiveDate     pgtype.Date        `json:"effective_date"`
	Status            string             `json:"status"`
	Reason            string             `json:"reason"`
	RequestedByUserID pgtype.UUID        `json:"requested_by_user_id"`
	ApprovedByUserID  pgtype.UUID        `json:"approved_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Party struct {
	ID pgtype.UUID `json:"id"`
	// Type of party: person or organization
	PartyType         string      `json:"party_type"`
	PartyCode         string      `json:"party_code"`
	DisplayName       string      `json:"display_name"`
	FullName          pgtype.Text `json:"full_name"`
	FirstName         pgtype.Text `json:"first_name"`
	MiddleName        pgtype.Text `json:"middle_name"`
	LastName          pgtype.Text `json:"last_name"`
	OrganizationName  pgtype.Text `json:"organization_name"`
	PrimaryPhone      string      `json:"primary_phone"`
	SecondaryPhone    pgtype.Text `json:"secondary_phone"`
	PrimaryEmail      pgtype.Text `json:"primary_email"`
	DateOfBirth       pgtype.Date `json:"date_of_birth"`
	Nationality       pgtype.Text `json:"nationality"`
	NationalIDNo      pgtype.Text `json:"national_id_no"`
	PassportNo        pgtype.Text `json:"passport_no"`
	RegistrationNo    pgtype.Text `json:"registration_no"`
	TaxNo             pgtype.Text `json:"tax_no"`
	PreferredLanguage string      `json:"preferred_language"`
	LegacyRef         pgtype.Text `json:"legacy_ref"`
	Notes             pgtype.Text `json:"notes"`
	// Party status: active, inactive, or blocked
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Payment struct {
	ID               pgtype.UUID        `json:"id"`
	BusinessEntityID pgtype.UUID        `json:"business_entity_id"`
	BranchID         pgtype.UUID        `json:"branch_id"`
	PartyID          pgtype.UUID        `json:"party_id"`
	PaymentNo        string             `json:"payment_no"`
	ReceiptNo        pgtype.Text        `json:"receipt_no"`
	PaymentDate      pgtype.Date        `json:"payment_date"`
	PaymentMethod    string             `json:"payment_method"`
	CurrencyCode     string             `json:"currency_code"`
	AmountReceived   pgtype.Numeric     `json:"amount_received"`
	UnappliedAmount  pgtype.Numeric     `json:"unapplied_amount"`
	Status           string             `json:"status"`
	ReferenceNo      pgtype.Text        `json:"reference_no"`
	Notes            pgtype.Text        `json:"notes"`
	ReceivedByUserID pgtype.UUID        `json:"received_by_user_id"`
	PostedAt         pgtype.Timestamptz `json:"posted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PaymentAllocation struct {
	ID              pgtype.UUID        `json:"id"`
	PaymentID       pgtype.UUID        `json:"payment_id"`
	ReceivableID    pgtype.UUID        `json:"receivable_id"`
	AllocatedAmount pgtype.Numeric     `json:"allocated_amount"`
	AllocationDate  pgtype.Date        `json:"allocation_date"`
	AllocationOrder int16              `json:"allocation_order"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID pgtype.UUID `json:"id"`
	// Machine-readable permission identifier, e.g. sales.contract.activate
	Key string `json:"key"`
	// Domain classifier: inventory, sales, rentals, finance, sc, utility, approvals, admin
	Module      string             `json:"module"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      pgtype.Text        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID               pgtype.UUID `json:"id"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	PrimaryBranchID  pgtype.UUID `json:"primary_branch_id"`
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	DisplayName      pgtype.Text `json:"display_name"`
	// residential, commercial, mixed, managed
	ProjectType string `json:"project_type"`
	// tower, compound, villa_community, mixed, flat
	StructureType   string             `json:"structure_type"`
	Status          string             `json:"status"`
	Country         string             `json:"country"`
	City            pgtype.Text        `json:"city"`
	DistrictArea    pgtype.Text        `json:"district_area"`
	AddressText     pgtype.Text        `json:"address_text"`
	DefaultCurrency string             `json:"default_currency"`
	LaunchDate      pgtype.Date        `json:"launch_date"`
	HandoverDate    pgtype.Date        `json:"handover_date"`
	Notes           pgtype.Text        `json:"notes"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Receivable struct {
	ID                pgtype.UUID        `json:"id"`
	BusinessEntityID  pgtype.UUID        `json:"business_entity_id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	PartyID           pgtype.UUID        `json:"party_id"`
	UnitID            pgtype.UUID        `json:"unit_id"`
	SourceModule      string             `json:"source_module"`
	SourceRecordType  string             `json:"source_record_type"`
	SourceRecordID    pgtype.UUID        `json:"source_record_id"`
	ReceivableNo      pgtype.Text        `json:"receivable_no"`
	ReceivableDate    pgtype.Date        `json:"receivable_date"`
	DueDate           pgtype.Date        `json:"due_date"`
	CurrencyCode      string             `json:"currency_code"`
	OriginalAmount    pgtype.Numeric     `json:"original_amount"`
	AdjustedAmount    pgtype.Numeric     `json:"adjusted_amount"`
	PaidAmount        pgtype.Numeric     `json:"paid_amount"`
	CreditedAmount    pgtype.Numeric     `json:"credited_amount"`
	OutstandingAmount pgtype.Numeric     `json:"outstanding_amount"`
	Status            string             `json:"status"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ResponsibilityAssignment struct {
	ID                 pgtype.UUID `json:"id"`
	UnitID             pgtype.UUID `json:"unit_id"`
	PartyID            pgtype.UUID `json:"party_id"`
	ResponsibilityType string      `json:"responsibility_type"`
	EffectiveFrom      pgtype.Date `json:"effective_from"`
	EffectiveTo        pgtype.Date `json:"effective_to"`
	// Assignment status: active or inactive
	Status    string             `json:"status"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID           pgtype.UUID        `json:"id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StructureNode struct {
	ID                    pgtype.UUID `json:"id"`
	ProjectID             pgtype.UUID `json:"project_id"`
	ParentStructureNodeID pgtype.UUID `json:"parent_structure_node_id"`
	// building, tower, block, cluster, floor
	NodeType     string             `json:"node_type"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	DisplayOrder int32              `json:"display_order"`
	Status       string             `json:"status"`
	IsActive     bool               `json:"is_active"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Task       string             `json:"task"`
	IsComplete bool               `json:"is_complete"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Unit struct {
	ID               pgtype.UUID `json:"id"`
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	StructureNodeID  pgtype.UUID `json:"structure_node_id"`
	ParentUnitID     pgtype.UUID `json:"parent_unit_id"`
	// apartment, villa, retail, office, parking, storage, townhouse
	UnitType string `json:"unit_type"`
	// sale_only, rent_only, sale_or_rent, internal_use, inactive
	CommercialDisposition string         `json:"commercial_disposition"`
	UnitCode              string         `json:"unit_code"`
	DisplayCode           pgtype.Text    `json:"display_code"`
	UnitNo                pgtype.Text    `json:"unit_no"`
	FloorValue            pgtype.Text    `json:"floor_value"`
	FloorSortValue        pgtype.Int4    `json:"floor_sort_value"`
	SectionNo             pgtype.Text    `json:"section_no"`
	EntranceNo            pgtype.Text    `json:"entrance_no"`
	BedroomCount          pgtype.Int2    `json:"bedroom_count"`
	BathroomCount         pgtype.Int2    `json:"bathroom_count"`
	AreaGrossSqm          pgtype.Numeric `json:"area_gross_sqm"`
	AreaNetSqm            pgtype.Numeric `json:"area_net_sqm"`
	AreaChargeableSqm     pgtype.Numeric `json:"area_chargeable_sqm"`
	LandAreaSqm           pgtype.Numeric `json:"land_area_sqm"`
	FacingDirection       pgtype.Text    `json:"facing_direction"`
	// available, reserved, sold, leased, owner_occupied, inactive
	InventoryStatus string `json:"inventory_status"`
	// available, reserved, sold, not_for_sale
	SalesStatus string `json:"sales_status"`
	// vacant, occupied, owner_occupied
	OccupancyStatus string `json:"occupancy_status"`
	// none, under_maintenance, restricted
	MaintenanceStatus string             `json:"maintenance_status"`
	ListPriceAmount   pgtype.Numeric     `json:"list_price_amount"`
	ListPriceCurrency string             `json:"list_price_currency"`
	ValuationAmount   pgtype.Numeric     `json:"valuation_amount"`
	IsActive          bool               `json:"is_active"`
	MetadataJson      []byte             `json:"metadata_json"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UnitOwnership struct {
	ID              pgtype.UUID    `json:"id"`
	UnitID          pgtype.UUID    `json:"unit_id"`
	PartyID         pgtype.UUID    `json:"party_id"`
	SharePercentage pgtype.Numeric `json:"share_percentage"`
	EffectiveFrom   pgtype.Date    `json:"effective_from"`
	EffectiveTo     pgtype.Date    `json:"effective_to"`
	// Ownership status: active or inactive
	Status    string             `json:"status"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserRoleScopeAssignment struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	ScopeType string             `json:"scope_type"`
	ScopeID   pgtype.UUID        `json:"scope_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
