// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      pgtype.Text        `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Task       string             `json:"task"`
	IsComplete bool               `json:"is_complete"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
