// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: party.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeResponsibilityAssignment = `-- name: CloseResponsibilityAssignment :one
UPDATE public.responsibility_assignments SET
    effective_to = $2::date,
    status = 'inactive'
WHERE id = $1
RETURNING id, unit_id, party_id, responsibility_type, effective_from, effective_to, status, notes, created_at, updated_at
`

type CloseResponsibilityAssignmentParams struct {
	ID          pgtype.UUID `json:"id"`
	EffectiveTo pgtype.Date `json:"effective_to"`
}

func (q *Queries) CloseResponsibilityAssignment(ctx context.Context, arg CloseResponsibilityAssignmentParams) (ResponsibilityAssignment, error) {
	row := q.db.QueryRow(ctx, closeResponsibilityAssignment, arg.ID, arg.EffectiveTo)
	var i ResponsibilityAssignment
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PartyID,
		&i.ResponsibilityType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeUnitOwnership = `-- name: CloseUnitOwnership :one
UPDATE public.unit_ownerships SET
    effective_to = $2::date,
    status = 'inactive'
WHERE id = $1
RETURNING id, unit_id, party_id, share_percentage, effective_from, effective_to, status, notes, created_at, updated_at
`

type CloseUnitOwnershipParams struct {
	ID          pgtype.UUID `json:"id"`
	EffectiveTo pgtype.Date `json:"effective_to"`
}

func (q *Queries) CloseUnitOwnership(ctx context.Context, arg CloseUnitOwnershipParams) (UnitOwnership, error) {
	row := q.db.QueryRow(ctx, closeUnitOwnership, arg.ID, arg.EffectiveTo)
	var i UnitOwnership
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PartyID,
		&i.SharePercentage,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countParties = `-- name: CountParties :one
SELECT COUNT(*)::bigint FROM public.parties
WHERE ($1::text IS NULL OR party_type = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
`

type CountPartiesParams struct {
	PartyType pgtype.Text `json:"party_type"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) CountParties(ctx context.Context, arg CountPartiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParties, arg.PartyType, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countResponsibilityAssignments = `-- name: CountResponsibilityAssignments :one
SELECT COUNT(*)::bigint FROM public.responsibility_assignments
WHERE unit_id = $1::uuid
  AND ($2::text IS NULL OR responsibility_type = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountResponsibilityAssignmentsParams struct {
	UnitID             pgtype.UUID `json:"unit_id"`
	ResponsibilityType pgtype.Text `json:"responsibility_type"`
	Status             pgtype.Text `json:"status"`
}

func (q *Queries) CountResponsibilityAssignments(ctx context.Context, arg CountResponsibilityAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResponsibilityAssignments, arg.UnitID, arg.ResponsibilityType, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnitOwnerships = `-- name: CountUnitOwnerships :one
SELECT COUNT(*)::bigint FROM public.unit_ownerships
WHERE unit_id = $1::uuid
  AND ($2::text IS NULL OR status = $2::text)
`

type CountUnitOwnershipsParams struct {
	UnitID pgtype.UUID `json:"unit_id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) CountUnitOwnerships(ctx context.Context, arg CountUnitOwnershipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnitOwnerships, arg.UnitID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createParty = `-- name: CreateParty :one
INSERT INTO public.parties (
    party_type,
    party_code,
    display_name,
    full_name,
    first_name,
    middle_name,
    last_name,
    organization_name,
    primary_phone,
    secondary_phone,
    primary_email,
    date_of_birth,
    nationality,
    national_id_no,
    passport_no,
    registration_no,
    tax_no,
    preferred_language,
    legacy_ref,
    notes,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
) RETURNING id, party_type, party_code, display_name, full_name, first_name, middle_name, last_name, organization_name, primary_phone, secondary_phone, primary_email, date_of_birth, nationality, national_id_no, passport_no, registration_no, tax_no, preferred_language, legacy_ref, notes, status, created_at, updated_at
`

type CreatePartyParams struct {
	PartyType         string      `json:"party_type"`
	PartyCode         string      `json:"party_code"`
	DisplayName       string      `json:"display_name"`
	FullName          pgtype.Text `json:"full_name"`
	FirstName         pgtype.Text `json:"first_name"`
	MiddleName        pgtype.Text `json:"middle_name"`
	LastName          pgtype.Text `json:"last_name"`
	OrganizationName  pgtype.Text `json:"organization_name"`
	PrimaryPhone      string      `json:"primary_phone"`
	SecondaryPhone    pgtype.Text `json:"secondary_phone"`
	PrimaryEmail      pgtype.Text `json:"primary_email"`
	DateOfBirth       pgtype.Date `json:"date_of_birth"`
	Nationality       pgtype.Text `json:"nationality"`
	NationalIDNo      pgtype.Text `json:"national_id_no"`
	PassportNo        pgtype.Text `json:"passport_no"`
	RegistrationNo    pgtype.Text `json:"registration_no"`
	TaxNo             pgtype.Text `json:"tax_no"`
	PreferredLanguage string      `json:"preferred_language"`
	LegacyRef         pgtype.Text `json:"legacy_ref"`
	Notes             pgtype.Text `json:"notes"`
	Status            string      `json:"status"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.PartyType,
		arg.PartyCode,
		arg.DisplayName,
		arg.FullName,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.OrganizationName,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.PrimaryEmail,
		arg.DateOfBirth,
		arg.Nationality,
		arg.NationalIDNo,
		arg.PassportNo,
		arg.RegistrationNo,
		arg.TaxNo,
		arg.PreferredLanguage,
		arg.LegacyRef,
		arg.Notes,
		arg.Status,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.PartyType,
		&i.PartyCode,
		&i.DisplayName,
		&i.FullName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OrganizationName,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.PrimaryEmail,
		&i.DateOfBirth,
		&i.Nationality,
		&i.NationalIDNo,
		&i.PassportNo,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.PreferredLanguage,
		&i.LegacyRef,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResponsibilityAssignment = `-- name: CreateResponsibilityAssignment :one
INSERT INTO public.responsibility_assignments (
    unit_id,
    party_id,
    responsibility_type,
    effective_from,
    effective_to,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, unit_id, party_id, responsibility_type, effective_from, effective_to, status, notes, created_at, updated_at
`

type CreateResponsibilityAssignmentParams struct {
	UnitID             pgtype.UUID `json:"unit_id"`
	PartyID            pgtype.UUID `json:"party_id"`
	ResponsibilityType string      `json:"responsibility_type"`
	EffectiveFrom      pgtype.Date `json:"effective_from"`
	EffectiveTo        pgtype.Date `json:"effective_to"`
	Status             string      `json:"status"`
	Notes              pgtype.Text `json:"notes"`
}

func (q *Queries) CreateResponsibilityAssignment(ctx context.Context, arg CreateResponsibilityAssignmentParams) (ResponsibilityAssignment, error) {
	row := q.db.QueryRow(ctx, createResponsibilityAssignment,
		arg.UnitID,
		arg.PartyID,
		arg.ResponsibilityType,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Status,
		arg.Notes,
	)
	var i ResponsibilityAssignment
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PartyID,
		&i.ResponsibilityType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnitOwnership = `-- name: CreateUnitOwnership :one
INSERT INTO public.unit_ownerships (
    unit_id,
    party_id,
    share_percentage,
    effective_from,
    effective_to,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, unit_id, party_id, share_percentage, effective_from, effective_to, status, notes, created_at, updated_at
`

type CreateUnitOwnershipParams struct {
	UnitID          pgtype.UUID    `json:"unit_id"`
	PartyID         pgtype.UUID    `json:"party_id"`
	SharePercentage pgtype.Numeric `json:"share_percentage"`
	EffectiveFrom   pgtype.Date    `json:"effective_from"`
	EffectiveTo     pgtype.Date    `json:"effective_to"`
	Status          string         `json:"status"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateUnitOwnership(ctx context.Context, arg CreateUnitOwnershipParams) (UnitOwnership, error) {
	row := q.db.QueryRow(ctx, createUnitOwnership,
		arg.UnitID,
		arg.PartyID,
		arg.SharePercentage,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Status,
		arg.Notes,
	)
	var i UnitOwnership
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PartyID,
		&i.SharePercentage,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveResponsibilityAssignment = `-- name: GetActiveResponsibilityAssignment :one
SELECT id, unit_id, party_id, responsibility_type, effective_from, effective_to, status, notes, created_at, updated_at FROM public.responsibility_assignments
WHERE unit_id = $1
  AND responsibility_type = $2
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to > $3)
  AND status = 'active'
ORDER BY effective_from DESC
LIMIT 1
`

type GetActiveResponsibilityAssignmentParams struct {
	UnitID             pgtype.UUID `json:"unit_id"`
	ResponsibilityType string      `json:"responsibility_type"`
	EffectiveFrom      pgtype.Date `json:"effective_from"`
}

func (q *Queries) GetActiveResponsibilityAssignment(ctx context.Context, arg GetActiveResponsibilityAssignmentParams) (ResponsibilityAssignment, error) {
	row := q.db.QueryRow(ctx, getActiveResponsibilityAssignment, arg.UnitID, arg.ResponsibilityType, arg.EffectiveFrom)
	var i ResponsibilityAssignment
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.PartyID,
		&i.ResponsibilityType,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParty = `-- name: GetParty :one
SELECT id, party_type, party_code, display_name, full_name, first_name, middle_name, last_name, organization_name, primary_phone, secondary_phone, primary_email, date_of_birth, nationality, national_id_no, passport_no, registration_no, tax_no, preferred_language, legacy_ref, notes, status, created_at, updated_at FROM public.parties WHERE id = $1
`

func (q *Queries) GetParty(ctx context.Context, id pgtype.UUID) (Party, error) {
	row := q.db.QueryRow(ctx, getParty, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.PartyType,
		&i.PartyCode,
		&i.DisplayName,
		&i.FullName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OrganizationName,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.PrimaryEmail,
		&i.DateOfBirth,
		&i.Nationality,
		&i.NationalIDNo,
		&i.PassportNo,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.PreferredLanguage,
		&i.LegacyRef,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParties = `-- name: ListParties :many


SELECT id, party_type, party_code, display_name, full_name, first_name, middle_name, last_name, organization_name, primary_phone, secondary_phone, primary_email, date_of_birth, nationality, national_id_no, passport_no, registration_no, tax_no, preferred_language, legacy_ref, notes, status, created_at, updated_at FROM public.parties
WHERE ($1::text IS NULL OR party_type = $1::text)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY display_name ASC
LIMIT $4::int OFFSET $3::int
`

type ListPartiesParams struct {
	PartyType pgtype.Text `json:"party_type"`
	Status    pgtype.Text `json:"status"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

// =============================================================================
// Party Domain Queries
// =============================================================================
// =============================================================================
// Parties
// =============================================================================
func (q *Queries) ListParties(ctx context.Context, arg ListPartiesParams) ([]Party, error) {
	rows, err := q.db.Query(ctx, listParties,
		arg.PartyType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.PartyType,
			&i.PartyCode,
			&i.DisplayName,
			&i.FullName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.OrganizationName,
			&i.PrimaryPhone,
			&i.SecondaryPhone,
			&i.PrimaryEmail,
			&i.DateOfBirth,
			&i.Nationality,
			&i.NationalIDNo,
			&i.PassportNo,
			&i.RegistrationNo,
			&i.TaxNo,
			&i.PreferredLanguage,
			&i.LegacyRef,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsibilityAssignments = `-- name: ListResponsibilityAssignments :many

SELECT id, unit_id, party_id, responsibility_type, effective_from, effective_to, status, notes, created_at, updated_at FROM public.responsibility_assignments
WHERE unit_id = $1::uuid
  AND ($2::text IS NULL OR responsibility_type = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY effective_from DESC
LIMIT $5::int OFFSET $4::int
`

type ListResponsibilityAssignmentsParams struct {
	UnitID             pgtype.UUID `json:"unit_id"`
	ResponsibilityType pgtype.Text `json:"responsibility_type"`
	Status             pgtype.Text `json:"status"`
	Offset             int32       `json:"offset"`
	Limit              int32       `json:"limit"`
}

// =============================================================================
// Responsibility Assignments
// =============================================================================
func (q *Queries) ListResponsibilityAssignments(ctx context.Context, arg ListResponsibilityAssignmentsParams) ([]ResponsibilityAssignment, error) {
	rows, err := q.db.Query(ctx, listResponsibilityAssignments,
		arg.UnitID,
		arg.ResponsibilityType,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResponsibilityAssignment{}
	for rows.Next() {
		var i ResponsibilityAssignment
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.PartyID,
			&i.ResponsibilityType,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitOwnerships = `-- name: ListUnitOwnerships :many

SELECT id, unit_id, party_id, share_percentage, effective_from, effective_to, status, notes, created_at, updated_at FROM public.unit_ownerships
WHERE unit_id = $1::uuid
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY effective_from DESC
LIMIT $4::int OFFSET $3::int
`

type ListUnitOwnershipsParams struct {
	UnitID pgtype.UUID `json:"unit_id"`
	Status pgtype.Text `json:"status"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

// =============================================================================
// Unit Ownerships
// =============================================================================
func (q *Queries) ListUnitOwnerships(ctx context.Context, arg ListUnitOwnershipsParams) ([]UnitOwnership, error) {
	rows, err := q.db.Query(ctx, listUnitOwnerships,
		arg.UnitID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitOwnership{}
	for rows.Next() {
		var i UnitOwnership
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.PartyID,
			&i.SharePercentage,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParty = `-- name: UpdateParty :one
UPDATE public.parties SET
    party_type = COALESCE($1::text, party_type),
    display_name = COALESCE($2::text, display_name),
    full_name = COALESCE($3::text, full_name),
    first_name = COALESCE($4::text, first_name),
    middle_name = COALESCE($5::text, middle_name),
    last_name = COALESCE($6::text, last_name),
    organization_name = COALESCE($7::text, organization_name),
    primary_phone = COALESCE($8::text, primary_phone),
    secondary_phone = COALESCE($9::text, secondary_phone),
    primary_email = COALESCE($10::text, primary_email),
    date_of_birth = COALESCE($11::date, date_of_birth),
    nationality = COALESCE($12::text, nationality),
    national_id_no = COALESCE($13::text, national_id_no),
    passport_no = COALESCE($14::text, passport_no),
    registration_no = COALESCE($15::text, registration_no),
    tax_no = COALESCE($16::text, tax_no),
    preferred_language = COALESCE($17::text, preferred_language),
    legacy_ref = COALESCE($18::text, legacy_ref),
    notes = COALESCE($19::text, notes),
    status = COALESCE($20::text, status)
WHERE id = $21::uuid
RETURNING id, party_type, party_code, display_name, full_name, first_name, middle_name, last_name, organization_name, primary_phone, secondary_phone, primary_email, date_of_birth, nationality, national_id_no, passport_no, registration_no, tax_no, preferred_language, legacy_ref, notes, status, created_at, updated_at
`

type UpdatePartyParams struct {
	PartyType         pgtype.Text `json:"party_type"`
	DisplayName       pgtype.Text `json:"display_name"`
	FullName          pgtype.Text `json:"full_name"`
	FirstName         pgtype.Text `json:"first_name"`
	MiddleName        pgtype.Text `json:"middle_name"`
	LastName          pgtype.Text `json:"last_name"`
	OrganizationName  pgtype.Text `json:"organization_name"`
	PrimaryPhone      pgtype.Text `json:"primary_phone"`
	SecondaryPhone    pgtype.Text `json:"secondary_phone"`
	PrimaryEmail      pgtype.Text `json:"primary_email"`
	DateOfBirth       pgtype.Date `json:"date_of_birth"`
	Nationality       pgtype.Text `json:"nationality"`
	NationalIDNo      pgtype.Text `json:"national_id_no"`
	PassportNo        pgtype.Text `json:"passport_no"`
	RegistrationNo    pgtype.Text `json:"registration_no"`
	TaxNo             pgtype.Text `json:"tax_no"`
	PreferredLanguage pgtype.Text `json:"preferred_language"`
	LegacyRef         pgtype.Text `json:"legacy_ref"`
	Notes             pgtype.Text `json:"notes"`
	Status            pgtype.Text `json:"status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.PartyType,
		arg.DisplayName,
		arg.FullName,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.OrganizationName,
		arg.PrimaryPhone,
		arg.SecondaryPhone,
		arg.PrimaryEmail,
		arg.DateOfBirth,
		arg.Nationality,
		arg.NationalIDNo,
		arg.PassportNo,
		arg.RegistrationNo,
		arg.TaxNo,
		arg.PreferredLanguage,
		arg.LegacyRef,
		arg.Notes,
		arg.Status,
		arg.ID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.PartyType,
		&i.PartyCode,
		&i.DisplayName,
		&i.FullName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OrganizationName,
		&i.PrimaryPhone,
		&i.SecondaryPhone,
		&i.PrimaryEmail,
		&i.DateOfBirth,
		&i.Nationality,
		&i.NationalIDNo,
		&i.PassportNo,
		&i.RegistrationNo,
		&i.TaxNo,
		&i.PreferredLanguage,
		&i.LegacyRef,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
