// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	GetTodosForUser(ctx context.Context, userID pgtype.UUID) ([]Todo, error)
	ToggleTodo(ctx context.Context, arg ToggleTodoParams) error
}

var _ Querier = (*Queries)(nil)
