// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodoRLS(ctx context.Context, task string) (Todo, error)
	DeleteTodoRLS(ctx context.Context, id pgtype.UUID) error
	GetTodoByIDRLS(ctx context.Context, id pgtype.UUID) (Todo, error)
	// RLS-based queries (rely on auth.uid() via GUC variables)
	// These must be used within a transaction with GUC injection
	GetTodosRLS(ctx context.Context) ([]Todo, error)
	ToggleTodoRLS(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
