// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rentals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeAllActiveLeaseParties = `-- name: CloseAllActiveLeaseParties :many
UPDATE public.lease_parties
SET effective_to = $2, status = 'closed', updated_at = timezone('utc', now())
WHERE lease_contract_id = $1 AND status = 'active'
RETURNING id, lease_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CloseAllActiveLeasePartiesParams struct {
	LeaseContractID pgtype.UUID `json:"lease_contract_id"`
	EffectiveTo     pgtype.Date `json:"effective_to"`
}

// Close every active lease_parties row for a lease (tenants, co-tenants, guarantors).
// Used by termination apply path so guarantor history is closed alongside tenant history.
func (q *Queries) CloseAllActiveLeaseParties(ctx context.Context, arg CloseAllActiveLeasePartiesParams) ([]LeaseParty, error) {
	rows, err := q.db.Query(ctx, closeAllActiveLeaseParties, arg.LeaseContractID, arg.EffectiveTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaseParty{}
	for rows.Next() {
		var i LeaseParty
		if err := rows.Scan(
			&i.ID,
			&i.LeaseContractID,
			&i.PartyID,
			&i.Role,
			&i.IsPrimary,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeLeaseParty = `-- name: CloseLeaseParty :one
UPDATE public.lease_parties
SET effective_to = $2, status = 'closed', updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'active'
RETURNING id, lease_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CloseLeasePartyParams struct {
	ID          pgtype.UUID `json:"id"`
	EffectiveTo pgtype.Date `json:"effective_to"`
}

func (q *Queries) CloseLeaseParty(ctx context.Context, arg CloseLeasePartyParams) (LeaseParty, error) {
	row := q.db.QueryRow(ctx, closeLeaseParty, arg.ID, arg.EffectiveTo)
	var i LeaseParty
	err := row.Scan(
		&i.ID,
		&i.LeaseContractID,
		&i.PartyID,
		&i.Role,
		&i.IsPrimary,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countLeaseBills = `-- name: CountLeaseBills :one
SELECT COUNT(*)::bigint FROM public.lease_bills
WHERE ($1::uuid IS NULL OR lease_contract_id = $1::uuid)
  AND ($2::uuid IS NULL OR unit_id = $2::uuid)
  AND ($3::uuid IS NULL OR responsible_party_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
`

type CountLeaseBillsParams struct {
	LeaseContractID    pgtype.UUID `json:"lease_contract_id"`
	UnitID             pgtype.UUID `json:"unit_id"`
	ResponsiblePartyID pgtype.UUID `json:"responsible_party_id"`
	Status             pgtype.Text `json:"status"`
}

func (q *Queries) CountLeaseBills(ctx context.Context, arg CountLeaseBillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaseBills,
		arg.LeaseContractID,
		arg.UnitID,
		arg.ResponsiblePartyID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLeaseContracts = `-- name: CountLeaseContracts :one
SELECT COUNT(*)::bigint FROM public.lease_contracts
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR primary_tenant_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
`

type CountLeaseContractsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	PrimaryTenantID  pgtype.UUID `json:"primary_tenant_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountLeaseContracts(ctx context.Context, arg CountLeaseContractsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLeaseContracts,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryTenantID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLeaseBill = `-- name: CreateLeaseBill :one
INSERT INTO public.lease_bills (
    business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id,
    billing_period_start, billing_period_end, due_date,
    billing_interval_value, billing_interval_unit,
    billed_amount, currency_code, is_advance, status, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at
`

type CreateLeaseBillParams struct {
	BusinessEntityID     pgtype.UUID    `json:"business_entity_id"`
	BranchID             pgtype.UUID    `json:"branch_id"`
	LeaseContractID      pgtype.UUID    `json:"lease_contract_id"`
	UnitID               pgtype.UUID    `json:"unit_id"`
	ResponsiblePartyID   pgtype.UUID    `json:"responsible_party_id"`
	BillingPeriodStart   pgtype.Date    `json:"billing_period_start"`
	BillingPeriodEnd     pgtype.Date    `json:"billing_period_end"`
	DueDate              pgtype.Date    `json:"due_date"`
	BillingIntervalValue int16          `json:"billing_interval_value"`
	BillingIntervalUnit  string         `json:"billing_interval_unit"`
	BilledAmount         pgtype.Numeric `json:"billed_amount"`
	CurrencyCode         string         `json:"currency_code"`
	IsAdvance            bool           `json:"is_advance"`
	Status               string         `json:"status"`
	Notes                pgtype.Text    `json:"notes"`
}

// Idempotent insert: returns NULL via :execrows-style guard not available on :one,
// so we use ON CONFLICT DO NOTHING and the handler checks rows-returned vs requested.
// Callers MUST pre-check existing periods via ListLeaseBills if they need the existing row.
func (q *Queries) CreateLeaseBill(ctx context.Context, arg CreateLeaseBillParams) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, createLeaseBill,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.LeaseContractID,
		arg.UnitID,
		arg.ResponsiblePartyID,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.DueDate,
		arg.BillingIntervalValue,
		arg.BillingIntervalUnit,
		arg.BilledAmount,
		arg.CurrencyCode,
		arg.IsAdvance,
		arg.Status,
		arg.Notes,
	)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeaseContract = `-- name: CreateLeaseContract :one
INSERT INTO public.lease_contracts (
    business_entity_id, branch_id, project_id, unit_id, primary_tenant_id,
    renewed_from_lease_contract_id, lease_type, start_date, end_date,
    rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount,
    billing_interval_value, billing_interval_unit, billing_anchor_date,
    security_deposit_amount, advance_rent_amount, currency_code,
    notice_period_days, purpose_of_use, notes, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22, $23
)
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type CreateLeaseContractParams struct {
	BusinessEntityID           pgtype.UUID    `json:"business_entity_id"`
	BranchID                   pgtype.UUID    `json:"branch_id"`
	ProjectID                  pgtype.UUID    `json:"project_id"`
	UnitID                     pgtype.UUID    `json:"unit_id"`
	PrimaryTenantID            pgtype.UUID    `json:"primary_tenant_id"`
	RenewedFromLeaseContractID pgtype.UUID    `json:"renewed_from_lease_contract_id"`
	LeaseType                  string         `json:"lease_type"`
	StartDate                  pgtype.Date    `json:"start_date"`
	EndDate                    pgtype.Date    `json:"end_date"`
	RentPricingBasis           string         `json:"rent_pricing_basis"`
	AreaBasisSqm               pgtype.Numeric `json:"area_basis_sqm"`
	RatePerSqm                 pgtype.Numeric `json:"rate_per_sqm"`
	ContractualRentAmount      pgtype.Numeric `json:"contractual_rent_amount"`
	BillingIntervalValue       int16          `json:"billing_interval_value"`
	BillingIntervalUnit        string         `json:"billing_interval_unit"`
	BillingAnchorDate          pgtype.Date    `json:"billing_anchor_date"`
	SecurityDepositAmount      pgtype.Numeric `json:"security_deposit_amount"`
	AdvanceRentAmount          pgtype.Numeric `json:"advance_rent_amount"`
	CurrencyCode               string         `json:"currency_code"`
	NoticePeriodDays           pgtype.Int4    `json:"notice_period_days"`
	PurposeOfUse               pgtype.Text    `json:"purpose_of_use"`
	Notes                      pgtype.Text    `json:"notes"`
	CreatedByUserID            pgtype.UUID    `json:"created_by_user_id"`
}

func (q *Queries) CreateLeaseContract(ctx context.Context, arg CreateLeaseContractParams) (LeaseContract, error) {
	row := q.db.QueryRow(ctx, createLeaseContract,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryTenantID,
		arg.RenewedFromLeaseContractID,
		arg.LeaseType,
		arg.StartDate,
		arg.EndDate,
		arg.RentPricingBasis,
		arg.AreaBasisSqm,
		arg.RatePerSqm,
		arg.ContractualRentAmount,
		arg.BillingIntervalValue,
		arg.BillingIntervalUnit,
		arg.BillingAnchorDate,
		arg.SecurityDepositAmount,
		arg.AdvanceRentAmount,
		arg.CurrencyCode,
		arg.NoticePeriodDays,
		arg.PurposeOfUse,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i LeaseContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryTenantID,
		&i.RenewedFromLeaseContractID,
		&i.LeaseNo,
		&i.LeaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RentPricingBasis,
		&i.AreaBasisSqm,
		&i.RatePerSqm,
		&i.ContractualRentAmount,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BillingAnchorDate,
		&i.SecurityDepositAmount,
		&i.AdvanceRentAmount,
		&i.CurrencyCode,
		&i.NoticePeriodDays,
		&i.PurposeOfUse,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLeaseParty = `-- name: CreateLeaseParty :one
INSERT INTO public.lease_parties (
    lease_contract_id, party_id, role, is_primary, effective_from, effective_to, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, lease_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CreateLeasePartyParams struct {
	LeaseContractID pgtype.UUID `json:"lease_contract_id"`
	PartyID         pgtype.UUID `json:"party_id"`
	Role            string      `json:"role"`
	IsPrimary       bool        `json:"is_primary"`
	EffectiveFrom   pgtype.Date `json:"effective_from"`
	EffectiveTo     pgtype.Date `json:"effective_to"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateLeaseParty(ctx context.Context, arg CreateLeasePartyParams) (LeaseParty, error) {
	row := q.db.QueryRow(ctx, createLeaseParty,
		arg.LeaseContractID,
		arg.PartyID,
		arg.Role,
		arg.IsPrimary,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Status,
	)
	var i LeaseParty
	err := row.Scan(
		&i.ID,
		&i.LeaseContractID,
		&i.PartyID,
		&i.Role,
		&i.IsPrimary,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveLeaseContractForUnit = `-- name: GetActiveLeaseContractForUnit :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.lease_contracts WHERE unit_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveLeaseContractForUnit(ctx context.Context, unitID pgtype.UUID) (LeaseContract, error) {
	row := q.db.QueryRow(ctx, getActiveLeaseContractForUnit, unitID)
	var i LeaseContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryTenantID,
		&i.RenewedFromLeaseContractID,
		&i.LeaseNo,
		&i.LeaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RentPricingBasis,
		&i.AreaBasisSqm,
		&i.RatePerSqm,
		&i.ContractualRentAmount,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BillingAnchorDate,
		&i.SecurityDepositAmount,
		&i.AdvanceRentAmount,
		&i.CurrencyCode,
		&i.NoticePeriodDays,
		&i.PurposeOfUse,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRentalsApprovalRequest = `-- name: GetLatestRentalsApprovalRequest :one

SELECT id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at
FROM public.approval_requests
WHERE module = 'rentals'
  AND source_record_type = $1
  AND source_record_id = $2
  AND request_type = $3
ORDER BY submitted_at DESC
LIMIT 1
`

type GetLatestRentalsApprovalRequestParams struct {
	SourceRecordType string      `json:"source_record_type"`
	SourceRecordID   pgtype.UUID `json:"source_record_id"`
	RequestType      string      `json:"request_type"`
}

// =============================================================================
// Approval gate lookup (Phase 7 pattern)
// =============================================================================
func (q *Queries) GetLatestRentalsApprovalRequest(ctx context.Context, arg GetLatestRentalsApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getLatestRentalsApprovalRequest, arg.SourceRecordType, arg.SourceRecordID, arg.RequestType)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaseBill = `-- name: GetLeaseBill :one
SELECT id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at FROM public.lease_bills WHERE id = $1
`

func (q *Queries) GetLeaseBill(ctx context.Context, id pgtype.UUID) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, getLeaseBill, id)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaseBillForPeriod = `-- name: GetLeaseBillForPeriod :one
SELECT id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at FROM public.lease_bills
WHERE lease_contract_id = $1 AND billing_period_start = $2 AND billing_period_end = $3 AND is_advance = $4
`

type GetLeaseBillForPeriodParams struct {
	LeaseContractID    pgtype.UUID `json:"lease_contract_id"`
	BillingPeriodStart pgtype.Date `json:"billing_period_start"`
	BillingPeriodEnd   pgtype.Date `json:"billing_period_end"`
	IsAdvance          bool        `json:"is_advance"`
}

func (q *Queries) GetLeaseBillForPeriod(ctx context.Context, arg GetLeaseBillForPeriodParams) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, getLeaseBillForPeriod,
		arg.LeaseContractID,
		arg.BillingPeriodStart,
		arg.BillingPeriodEnd,
		arg.IsAdvance,
	)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaseContract = `-- name: GetLeaseContract :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.lease_contracts WHERE id = $1
`

func (q *Queries) GetLeaseContract(ctx context.Context, id pgtype.UUID) (LeaseContract, error) {
	row := q.db.QueryRow(ctx, getLeaseContract, id)
	var i LeaseContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryTenantID,
		&i.RenewedFromLeaseContractID,
		&i.LeaseNo,
		&i.LeaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RentPricingBasis,
		&i.AreaBasisSqm,
		&i.RatePerSqm,
		&i.ContractualRentAmount,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BillingAnchorDate,
		&i.SecurityDepositAmount,
		&i.AdvanceRentAmount,
		&i.CurrencyCode,
		&i.NoticePeriodDays,
		&i.PurposeOfUse,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const issueLeaseBill = `-- name: IssueLeaseBill :one
UPDATE public.lease_bills
SET status = 'issued', updated_at = timezone('utc', now())
WHERE id = $1 AND status = 'draft'
RETURNING id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at
`

func (q *Queries) IssueLeaseBill(ctx context.Context, id pgtype.UUID) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, issueLeaseBill, id)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkLeaseBillReceivable = `-- name: LinkLeaseBillReceivable :one
UPDATE public.lease_bills
SET receivable_id = $2, updated_at = timezone('utc', now())
WHERE id = $1 AND receivable_id IS NULL
RETURNING id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at
`

type LinkLeaseBillReceivableParams struct {
	ID           pgtype.UUID `json:"id"`
	ReceivableID pgtype.UUID `json:"receivable_id"`
}

func (q *Queries) LinkLeaseBillReceivable(ctx context.Context, arg LinkLeaseBillReceivableParams) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, linkLeaseBillReceivable, arg.ID, arg.ReceivableID)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaseBills = `-- name: ListLeaseBills :many

SELECT id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at FROM public.lease_bills
WHERE ($1::uuid IS NULL OR lease_contract_id = $1::uuid)
  AND ($2::uuid IS NULL OR unit_id = $2::uuid)
  AND ($3::uuid IS NULL OR responsible_party_id = $3::uuid)
  AND ($4::text IS NULL OR status = $4::text)
ORDER BY billing_period_start ASC
LIMIT $6::int OFFSET $5::int
`

type ListLeaseBillsParams struct {
	LeaseContractID    pgtype.UUID `json:"lease_contract_id"`
	UnitID             pgtype.UUID `json:"unit_id"`
	ResponsiblePartyID pgtype.UUID `json:"responsible_party_id"`
	Status             pgtype.Text `json:"status"`
	Offset             int32       `json:"offset"`
	Limit              int32       `json:"limit"`
}

// =============================================================================
// Lease Bills
// =============================================================================
func (q *Queries) ListLeaseBills(ctx context.Context, arg ListLeaseBillsParams) ([]LeaseBill, error) {
	rows, err := q.db.Query(ctx, listLeaseBills,
		arg.LeaseContractID,
		arg.UnitID,
		arg.ResponsiblePartyID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaseBill{}
	for rows.Next() {
		var i LeaseBill
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.LeaseContractID,
			&i.UnitID,
			&i.ResponsiblePartyID,
			&i.ReceivableID,
			&i.BillingPeriodStart,
			&i.BillingPeriodEnd,
			&i.DueDate,
			&i.BillingIntervalValue,
			&i.BillingIntervalUnit,
			&i.BilledAmount,
			&i.CurrencyCode,
			&i.IsAdvance,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaseContracts = `-- name: ListLeaseContracts :many


SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.lease_contracts
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR primary_tenant_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
ORDER BY created_at DESC
LIMIT $8::int OFFSET $7::int
`

type ListLeaseContractsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	PrimaryTenantID  pgtype.UUID `json:"primary_tenant_id"`
	Status           pgtype.Text `json:"status"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// backend/db/queries/rentals.sql
// =============================================================================
// Lease Contracts
// =============================================================================
func (q *Queries) ListLeaseContracts(ctx context.Context, arg ListLeaseContractsParams) ([]LeaseContract, error) {
	rows, err := q.db.Query(ctx, listLeaseContracts,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryTenantID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaseContract{}
	for rows.Next() {
		var i LeaseContract
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.ProjectID,
			&i.UnitID,
			&i.PrimaryTenantID,
			&i.RenewedFromLeaseContractID,
			&i.LeaseNo,
			&i.LeaseType,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.RentPricingBasis,
			&i.AreaBasisSqm,
			&i.RatePerSqm,
			&i.ContractualRentAmount,
			&i.BillingIntervalValue,
			&i.BillingIntervalUnit,
			&i.BillingAnchorDate,
			&i.SecurityDepositAmount,
			&i.AdvanceRentAmount,
			&i.CurrencyCode,
			&i.NoticePeriodDays,
			&i.PurposeOfUse,
			&i.Notes,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaseParties = `-- name: ListLeaseParties :many

SELECT id, lease_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at FROM public.lease_parties
WHERE lease_contract_id = $1
ORDER BY is_primary DESC, effective_from DESC
`

// =============================================================================
// Lease Parties (effective-dated)
// =============================================================================
func (q *Queries) ListLeaseParties(ctx context.Context, leaseContractID pgtype.UUID) ([]LeaseParty, error) {
	rows, err := q.db.Query(ctx, listLeaseParties, leaseContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaseParty{}
	for rows.Next() {
		var i LeaseParty
		if err := rows.Scan(
			&i.ID,
			&i.LeaseContractID,
			&i.PartyID,
			&i.Role,
			&i.IsPrimary,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaseContract = `-- name: UpdateLeaseContract :one
UPDATE public.lease_contracts SET
    lease_type = COALESCE($1::text, lease_type),
    start_date = COALESCE($2::date, start_date),
    end_date = COALESCE($3::date, end_date),
    rent_pricing_basis = COALESCE($4::text, rent_pricing_basis),
    area_basis_sqm = COALESCE($5::numeric, area_basis_sqm),
    rate_per_sqm = COALESCE($6::numeric, rate_per_sqm),
    contractual_rent_amount = COALESCE($7::numeric, contractual_rent_amount),
    billing_interval_value = COALESCE($8::smallint, billing_interval_value),
    billing_interval_unit = COALESCE($9::text, billing_interval_unit),
    billing_anchor_date = COALESCE($10::date, billing_anchor_date),
    security_deposit_amount = COALESCE($11::numeric, security_deposit_amount),
    advance_rent_amount = COALESCE($12::numeric, advance_rent_amount),
    notice_period_days = COALESCE($13::int, notice_period_days),
    purpose_of_use = COALESCE($14::text, purpose_of_use),
    notes = COALESCE($15::text, notes),
    updated_at = timezone('utc', now())
WHERE id = $16::uuid AND status = 'draft'
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateLeaseContractParams struct {
	LeaseType             pgtype.Text    `json:"lease_type"`
	StartDate             pgtype.Date    `json:"start_date"`
	EndDate               pgtype.Date    `json:"end_date"`
	RentPricingBasis      pgtype.Text    `json:"rent_pricing_basis"`
	AreaBasisSqm          pgtype.Numeric `json:"area_basis_sqm"`
	RatePerSqm            pgtype.Numeric `json:"rate_per_sqm"`
	ContractualRentAmount pgtype.Numeric `json:"contractual_rent_amount"`
	BillingIntervalValue  pgtype.Int2    `json:"billing_interval_value"`
	BillingIntervalUnit   pgtype.Text    `json:"billing_interval_unit"`
	BillingAnchorDate     pgtype.Date    `json:"billing_anchor_date"`
	SecurityDepositAmount pgtype.Numeric `json:"security_deposit_amount"`
	AdvanceRentAmount     pgtype.Numeric `json:"advance_rent_amount"`
	NoticePeriodDays      pgtype.Int4    `json:"notice_period_days"`
	PurposeOfUse          pgtype.Text    `json:"purpose_of_use"`
	Notes                 pgtype.Text    `json:"notes"`
	ID                    pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateLeaseContract(ctx context.Context, arg UpdateLeaseContractParams) (LeaseContract, error) {
	row := q.db.QueryRow(ctx, updateLeaseContract,
		arg.LeaseType,
		arg.StartDate,
		arg.EndDate,
		arg.RentPricingBasis,
		arg.AreaBasisSqm,
		arg.RatePerSqm,
		arg.ContractualRentAmount,
		arg.BillingIntervalValue,
		arg.BillingIntervalUnit,
		arg.BillingAnchorDate,
		arg.SecurityDepositAmount,
		arg.AdvanceRentAmount,
		arg.NoticePeriodDays,
		arg.PurposeOfUse,
		arg.Notes,
		arg.ID,
	)
	var i LeaseContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryTenantID,
		&i.RenewedFromLeaseContractID,
		&i.LeaseNo,
		&i.LeaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RentPricingBasis,
		&i.AreaBasisSqm,
		&i.RatePerSqm,
		&i.ContractualRentAmount,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BillingAnchorDate,
		&i.SecurityDepositAmount,
		&i.AdvanceRentAmount,
		&i.CurrencyCode,
		&i.NoticePeriodDays,
		&i.PurposeOfUse,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeaseContractStatus = `-- name: UpdateLeaseContractStatus :one
UPDATE public.lease_contracts
SET status = $2, updated_at = timezone('utc', now())
WHERE id = $1 AND status = $3
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_tenant_id, renewed_from_lease_contract_id, lease_no, lease_type, status, start_date, end_date, rent_pricing_basis, area_basis_sqm, rate_per_sqm, contractual_rent_amount, billing_interval_value, billing_interval_unit, billing_anchor_date, security_deposit_amount, advance_rent_amount, currency_code, notice_period_days, purpose_of_use, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateLeaseContractStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) UpdateLeaseContractStatus(ctx context.Context, arg UpdateLeaseContractStatusParams) (LeaseContract, error) {
	row := q.db.QueryRow(ctx, updateLeaseContractStatus, arg.ID, arg.Status, arg.Status_2)
	var i LeaseContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryTenantID,
		&i.RenewedFromLeaseContractID,
		&i.LeaseNo,
		&i.LeaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.RentPricingBasis,
		&i.AreaBasisSqm,
		&i.RatePerSqm,
		&i.ContractualRentAmount,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BillingAnchorDate,
		&i.SecurityDepositAmount,
		&i.AdvanceRentAmount,
		&i.CurrencyCode,
		&i.NoticePeriodDays,
		&i.PurposeOfUse,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidLeaseBill = `-- name: VoidLeaseBill :one
UPDATE public.lease_bills
SET status = 'voided', updated_at = timezone('utc', now())
WHERE id = $1 AND status IN ('draft', 'issued')
RETURNING id, business_entity_id, branch_id, lease_contract_id, unit_id, responsible_party_id, receivable_id, billing_period_start, billing_period_end, due_date, billing_interval_value, billing_interval_unit, billed_amount, currency_code, is_advance, status, notes, created_at, updated_at
`

func (q *Queries) VoidLeaseBill(ctx context.Context, id pgtype.UUID) (LeaseBill, error) {
	row := q.db.QueryRow(ctx, voidLeaseBill, id)
	var i LeaseBill
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.LeaseContractID,
		&i.UnitID,
		&i.ResponsiblePartyID,
		&i.ReceivableID,
		&i.BillingPeriodStart,
		&i.BillingPeriodEnd,
		&i.DueDate,
		&i.BillingIntervalValue,
		&i.BillingIntervalUnit,
		&i.BilledAmount,
		&i.CurrencyCode,
		&i.IsAdvance,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
