// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeActiveSalesContractPartiesForParty = `-- name: CloseActiveSalesContractPartiesForParty :many
UPDATE public.sales_contract_parties
SET effective_to = $3, status = 'inactive', updated_at = timezone('utc', now())
WHERE sales_contract_id = $1
  AND party_id = $2
  AND effective_to IS NULL
  AND status = 'active'
RETURNING id, sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CloseActiveSalesContractPartiesForPartyParams struct {
	SalesContractID pgtype.UUID `json:"sales_contract_id"`
	PartyID         pgtype.UUID `json:"party_id"`
	EffectiveTo     pgtype.Date `json:"effective_to"`
}

func (q *Queries) CloseActiveSalesContractPartiesForParty(ctx context.Context, arg CloseActiveSalesContractPartiesForPartyParams) ([]SalesContractParty, error) {
	rows, err := q.db.Query(ctx, closeActiveSalesContractPartiesForParty, arg.SalesContractID, arg.PartyID, arg.EffectiveTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesContractParty{}
	for rows.Next() {
		var i SalesContractParty
		if err := rows.Scan(
			&i.ID,
			&i.SalesContractID,
			&i.PartyID,
			&i.Role,
			&i.IsPrimary,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeSalesContractParty = `-- name: CloseSalesContractParty :one
UPDATE public.sales_contract_parties
SET effective_to = $2, status = 'inactive', updated_at = timezone('utc', now())
WHERE id = $1 AND effective_to IS NULL
RETURNING id, sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CloseSalesContractPartyParams struct {
	ID          pgtype.UUID `json:"id"`
	EffectiveTo pgtype.Date `json:"effective_to"`
}

func (q *Queries) CloseSalesContractParty(ctx context.Context, arg CloseSalesContractPartyParams) (SalesContractParty, error) {
	row := q.db.QueryRow(ctx, closeSalesContractParty, arg.ID, arg.EffectiveTo)
	var i SalesContractParty
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.PartyID,
		&i.Role,
		&i.IsPrimary,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPaymentPlanTemplates = `-- name: CountPaymentPlanTemplates :one
SELECT COUNT(*)::bigint FROM public.payment_plan_templates
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
`

type CountPaymentPlanTemplatesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountPaymentPlanTemplates(ctx context.Context, arg CountPaymentPlanTemplatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentPlanTemplates, arg.BusinessEntityID, arg.ProjectID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countReservations = `-- name: CountReservations :one
SELECT COUNT(*)::bigint FROM public.reservations
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR customer_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
`

type CountReservationsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	CustomerID       pgtype.UUID `json:"customer_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountReservations(ctx context.Context, arg CountReservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReservations,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.CustomerID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSalesContracts = `-- name: CountSalesContracts :one
SELECT COUNT(*)::bigint FROM public.sales_contracts
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR primary_buyer_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
`

type CountSalesContractsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	PrimaryBuyerID   pgtype.UUID `json:"primary_buyer_id"`
	Status           pgtype.Text `json:"status"`
}

func (q *Queries) CountSalesContracts(ctx context.Context, arg CountSalesContractsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesContracts,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryBuyerID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInstallmentScheduleLine = `-- name: CreateInstallmentScheduleLine :one
INSERT INTO public.installment_schedule_lines (
    sales_contract_id, receivable_id, line_no, due_date, line_type,
    description, principal_amount, penalty_amount_accrued,
    discount_amount_applied, amount_paid, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at
`

type CreateInstallmentScheduleLineParams struct {
	SalesContractID       pgtype.UUID    `json:"sales_contract_id"`
	ReceivableID          pgtype.UUID    `json:"receivable_id"`
	LineNo                int16          `json:"line_no"`
	DueDate               pgtype.Date    `json:"due_date"`
	LineType              string         `json:"line_type"`
	Description           pgtype.Text    `json:"description"`
	PrincipalAmount       pgtype.Numeric `json:"principal_amount"`
	PenaltyAmountAccrued  pgtype.Numeric `json:"penalty_amount_accrued"`
	DiscountAmountApplied pgtype.Numeric `json:"discount_amount_applied"`
	AmountPaid            pgtype.Numeric `json:"amount_paid"`
	Status                string         `json:"status"`
}

func (q *Queries) CreateInstallmentScheduleLine(ctx context.Context, arg CreateInstallmentScheduleLineParams) (InstallmentScheduleLine, error) {
	row := q.db.QueryRow(ctx, createInstallmentScheduleLine,
		arg.SalesContractID,
		arg.ReceivableID,
		arg.LineNo,
		arg.DueDate,
		arg.LineType,
		arg.Description,
		arg.PrincipalAmount,
		arg.PenaltyAmountAccrued,
		arg.DiscountAmountApplied,
		arg.AmountPaid,
		arg.Status,
	)
	var i InstallmentScheduleLine
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.ReceivableID,
		&i.LineNo,
		&i.DueDate,
		&i.LineType,
		&i.Description,
		&i.PrincipalAmount,
		&i.PenaltyAmountAccrued,
		&i.DiscountAmountApplied,
		&i.AmountPaid,
		&i.AmountOutstanding,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOwnershipTransfer = `-- name: CreateOwnershipTransfer :one

INSERT INTO public.ownership_transfers (
    business_entity_id, branch_id, project_id, unit_id, sales_contract_id,
    approval_request_id, transfer_type, from_party_id, to_party_id,
    effective_date, financial_treatment, transfer_fee_amount,
    transfer_fee_currency, notes, status, requested_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at
`

type CreateOwnershipTransferParams struct {
	BusinessEntityID    pgtype.UUID    `json:"business_entity_id"`
	BranchID            pgtype.UUID    `json:"branch_id"`
	ProjectID           pgtype.UUID    `json:"project_id"`
	UnitID              pgtype.UUID    `json:"unit_id"`
	SalesContractID     pgtype.UUID    `json:"sales_contract_id"`
	ApprovalRequestID   pgtype.UUID    `json:"approval_request_id"`
	TransferType        string         `json:"transfer_type"`
	FromPartyID         pgtype.UUID    `json:"from_party_id"`
	ToPartyID           pgtype.UUID    `json:"to_party_id"`
	EffectiveDate       pgtype.Date    `json:"effective_date"`
	FinancialTreatment  string         `json:"financial_treatment"`
	TransferFeeAmount   pgtype.Numeric `json:"transfer_fee_amount"`
	TransferFeeCurrency string         `json:"transfer_fee_currency"`
	Notes               pgtype.Text    `json:"notes"`
	Status              string         `json:"status"`
	RequestedByUserID   pgtype.UUID    `json:"requested_by_user_id"`
}

// =============================================================================
// Ownership Transfers
// =============================================================================
func (q *Queries) CreateOwnershipTransfer(ctx context.Context, arg CreateOwnershipTransferParams) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, createOwnershipTransfer,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.SalesContractID,
		arg.ApprovalRequestID,
		arg.TransferType,
		arg.FromPartyID,
		arg.ToPartyID,
		arg.EffectiveDate,
		arg.FinancialTreatment,
		arg.TransferFeeAmount,
		arg.TransferFeeCurrency,
		arg.Notes,
		arg.Status,
		arg.RequestedByUserID,
	)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentPlanTemplate = `-- name: CreatePaymentPlanTemplate :one
INSERT INTO public.payment_plan_templates (
    business_entity_id, project_id, code, name, status,
    frequency_type, installment_count, generation_rule_json, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, business_entity_id, project_id, code, name, status, frequency_type, installment_count, generation_rule_json, notes, created_at, updated_at
`

type CreatePaymentPlanTemplateParams struct {
	BusinessEntityID   pgtype.UUID `json:"business_entity_id"`
	ProjectID          pgtype.UUID `json:"project_id"`
	Code               string      `json:"code"`
	Name               string      `json:"name"`
	Status             string      `json:"status"`
	FrequencyType      string      `json:"frequency_type"`
	InstallmentCount   int32       `json:"installment_count"`
	GenerationRuleJson []byte      `json:"generation_rule_json"`
	Notes              pgtype.Text `json:"notes"`
}

func (q *Queries) CreatePaymentPlanTemplate(ctx context.Context, arg CreatePaymentPlanTemplateParams) (PaymentPlanTemplate, error) {
	row := q.db.QueryRow(ctx, createPaymentPlanTemplate,
		arg.BusinessEntityID,
		arg.ProjectID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.FrequencyType,
		arg.InstallmentCount,
		arg.GenerationRuleJson,
		arg.Notes,
	)
	var i PaymentPlanTemplate
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.ProjectID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.FrequencyType,
		&i.InstallmentCount,
		&i.GenerationRuleJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO public.reservations (
    business_entity_id, branch_id, project_id, unit_id, customer_id,
    expires_at, deposit_amount, deposit_currency, deposit_payment_id,
    quoted_price_amount, discount_amount, notes, created_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type CreateReservationParams struct {
	BusinessEntityID  pgtype.UUID        `json:"business_entity_id"`
	BranchID          pgtype.UUID        `json:"branch_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	UnitID            pgtype.UUID        `json:"unit_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	DepositAmount     pgtype.Numeric     `json:"deposit_amount"`
	DepositCurrency   string             `json:"deposit_currency"`
	DepositPaymentID  pgtype.UUID        `json:"deposit_payment_id"`
	QuotedPriceAmount pgtype.Numeric     `json:"quoted_price_amount"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.CustomerID,
		arg.ExpiresAt,
		arg.DepositAmount,
		arg.DepositCurrency,
		arg.DepositPaymentID,
		arg.QuotedPriceAmount,
		arg.DiscountAmount,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.CustomerID,
		&i.ReservationNo,
		&i.Status,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.DepositAmount,
		&i.DepositCurrency,
		&i.DepositPaymentID,
		&i.QuotedPriceAmount,
		&i.DiscountAmount,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesContract = `-- name: CreateSalesContract :one
INSERT INTO public.sales_contracts (
    business_entity_id, branch_id, project_id, unit_id, primary_buyer_id,
    source_reservation_id, contract_date, effective_date, sale_price_amount,
    sale_price_currency, discount_amount, net_contract_amount,
    down_payment_amount, financed_amount, payment_plan_template_id,
    handover_date_planned, notes, created_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type CreateSalesContractParams struct {
	BusinessEntityID      pgtype.UUID    `json:"business_entity_id"`
	BranchID              pgtype.UUID    `json:"branch_id"`
	ProjectID             pgtype.UUID    `json:"project_id"`
	UnitID                pgtype.UUID    `json:"unit_id"`
	PrimaryBuyerID        pgtype.UUID    `json:"primary_buyer_id"`
	SourceReservationID   pgtype.UUID    `json:"source_reservation_id"`
	ContractDate          pgtype.Date    `json:"contract_date"`
	EffectiveDate         pgtype.Date    `json:"effective_date"`
	SalePriceAmount       pgtype.Numeric `json:"sale_price_amount"`
	SalePriceCurrency     string         `json:"sale_price_currency"`
	DiscountAmount        pgtype.Numeric `json:"discount_amount"`
	NetContractAmount     pgtype.Numeric `json:"net_contract_amount"`
	DownPaymentAmount     pgtype.Numeric `json:"down_payment_amount"`
	FinancedAmount        pgtype.Numeric `json:"financed_amount"`
	PaymentPlanTemplateID pgtype.UUID    `json:"payment_plan_template_id"`
	HandoverDatePlanned   pgtype.Date    `json:"handover_date_planned"`
	Notes                 pgtype.Text    `json:"notes"`
	CreatedByUserID       pgtype.UUID    `json:"created_by_user_id"`
}

func (q *Queries) CreateSalesContract(ctx context.Context, arg CreateSalesContractParams) (SalesContract, error) {
	row := q.db.QueryRow(ctx, createSalesContract,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryBuyerID,
		arg.SourceReservationID,
		arg.ContractDate,
		arg.EffectiveDate,
		arg.SalePriceAmount,
		arg.SalePriceCurrency,
		arg.DiscountAmount,
		arg.NetContractAmount,
		arg.DownPaymentAmount,
		arg.FinancedAmount,
		arg.PaymentPlanTemplateID,
		arg.HandoverDatePlanned,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesContractParty = `-- name: CreateSalesContractParty :one
INSERT INTO public.sales_contract_parties (
    sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at
`

type CreateSalesContractPartyParams struct {
	SalesContractID pgtype.UUID `json:"sales_contract_id"`
	PartyID         pgtype.UUID `json:"party_id"`
	Role            string      `json:"role"`
	IsPrimary       bool        `json:"is_primary"`
	EffectiveFrom   pgtype.Date `json:"effective_from"`
	EffectiveTo     pgtype.Date `json:"effective_to"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateSalesContractParty(ctx context.Context, arg CreateSalesContractPartyParams) (SalesContractParty, error) {
	row := q.db.QueryRow(ctx, createSalesContractParty,
		arg.SalesContractID,
		arg.PartyID,
		arg.Role,
		arg.IsPrimary,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.Status,
	)
	var i SalesContractParty
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.PartyID,
		&i.Role,
		&i.IsPrimary,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireReservations = `-- name: ExpireReservations :many
UPDATE public.reservations
SET status = 'expired', updated_at = timezone('utc', now())
WHERE status = 'active' AND expires_at < timezone('utc', now())
RETURNING id
`

func (q *Queries) ExpireReservations(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, expireReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveReservationForUnit = `-- name: GetActiveReservationForUnit :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.reservations WHERE unit_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveReservationForUnit(ctx context.Context, unitID pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getActiveReservationForUnit, unitID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.CustomerID,
		&i.ReservationNo,
		&i.Status,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.DepositAmount,
		&i.DepositCurrency,
		&i.DepositPaymentID,
		&i.QuotedPriceAmount,
		&i.DiscountAmount,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSalesContractForUnit = `-- name: GetActiveSalesContractForUnit :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.sales_contracts WHERE unit_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveSalesContractForUnit(ctx context.Context, unitID pgtype.UUID) (SalesContract, error) {
	row := q.db.QueryRow(ctx, getActiveSalesContractForUnit, unitID)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSalesContractPartyForParty = `-- name: GetActiveSalesContractPartyForParty :one
SELECT id, sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at FROM public.sales_contract_parties
WHERE sales_contract_id = $1
  AND party_id = $2
  AND effective_to IS NULL
  AND status = 'active'
LIMIT 1
`

type GetActiveSalesContractPartyForPartyParams struct {
	SalesContractID pgtype.UUID `json:"sales_contract_id"`
	PartyID         pgtype.UUID `json:"party_id"`
}

func (q *Queries) GetActiveSalesContractPartyForParty(ctx context.Context, arg GetActiveSalesContractPartyForPartyParams) (SalesContractParty, error) {
	row := q.db.QueryRow(ctx, getActiveSalesContractPartyForParty, arg.SalesContractID, arg.PartyID)
	var i SalesContractParty
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.PartyID,
		&i.Role,
		&i.IsPrimary,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallmentScheduleLine = `-- name: GetInstallmentScheduleLine :one
SELECT id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at FROM public.installment_schedule_lines WHERE id = $1
`

func (q *Queries) GetInstallmentScheduleLine(ctx context.Context, id pgtype.UUID) (InstallmentScheduleLine, error) {
	row := q.db.QueryRow(ctx, getInstallmentScheduleLine, id)
	var i InstallmentScheduleLine
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.ReceivableID,
		&i.LineNo,
		&i.DueDate,
		&i.LineType,
		&i.Description,
		&i.PrincipalAmount,
		&i.PenaltyAmountAccrued,
		&i.DiscountAmountApplied,
		&i.AmountPaid,
		&i.AmountOutstanding,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSalesApprovalRequest = `-- name: GetLatestSalesApprovalRequest :one
SELECT id, business_entity_id, branch_id, approval_policy_id, module, request_type, source_record_type, source_record_id, requested_by_user_id, assigned_to_user_id, status, submitted_at, decided_at, decision_reason, payload_snapshot_json, created_at, updated_at
FROM public.approval_requests
WHERE module = 'sales'
  AND source_record_type = $1
  AND source_record_id = $2
  AND request_type = $3
ORDER BY submitted_at DESC
LIMIT 1
`

type GetLatestSalesApprovalRequestParams struct {
	SourceRecordType string      `json:"source_record_type"`
	SourceRecordID   pgtype.UUID `json:"source_record_id"`
	RequestType      string      `json:"request_type"`
}

func (q *Queries) GetLatestSalesApprovalRequest(ctx context.Context, arg GetLatestSalesApprovalRequestParams) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getLatestSalesApprovalRequest, arg.SourceRecordType, arg.SourceRecordID, arg.RequestType)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ApprovalPolicyID,
		&i.Module,
		&i.RequestType,
		&i.SourceRecordType,
		&i.SourceRecordID,
		&i.RequestedByUserID,
		&i.AssignedToUserID,
		&i.Status,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.DecisionReason,
		&i.PayloadSnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextScheduleLineNumber = `-- name: GetNextScheduleLineNumber :one
SELECT COALESCE(MAX(line_no), 0)::smallint + 1 AS next_line_no
FROM public.installment_schedule_lines
WHERE sales_contract_id = $1
`

func (q *Queries) GetNextScheduleLineNumber(ctx context.Context, salesContractID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextScheduleLineNumber, salesContractID)
	var next_line_no int32
	err := row.Scan(&next_line_no)
	return next_line_no, err
}

const getOwnershipTransfer = `-- name: GetOwnershipTransfer :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at FROM public.ownership_transfers WHERE id = $1
`

func (q *Queries) GetOwnershipTransfer(ctx context.Context, id pgtype.UUID) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, getOwnershipTransfer, id)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnershipTransferByApprovalRequest = `-- name: GetOwnershipTransferByApprovalRequest :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at FROM public.ownership_transfers WHERE approval_request_id = $1
`

func (q *Queries) GetOwnershipTransferByApprovalRequest(ctx context.Context, approvalRequestID pgtype.UUID) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, getOwnershipTransferByApprovalRequest, approvalRequestID)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentPlanTemplate = `-- name: GetPaymentPlanTemplate :one
SELECT id, business_entity_id, project_id, code, name, status, frequency_type, installment_count, generation_rule_json, notes, created_at, updated_at FROM public.payment_plan_templates WHERE id = $1
`

func (q *Queries) GetPaymentPlanTemplate(ctx context.Context, id pgtype.UUID) (PaymentPlanTemplate, error) {
	row := q.db.QueryRow(ctx, getPaymentPlanTemplate, id)
	var i PaymentPlanTemplate
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.ProjectID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.FrequencyType,
		&i.InstallmentCount,
		&i.GenerationRuleJson,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.reservations WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.CustomerID,
		&i.ReservationNo,
		&i.Status,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.DepositAmount,
		&i.DepositCurrency,
		&i.DepositPaymentID,
		&i.QuotedPriceAmount,
		&i.DiscountAmount,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesContract = `-- name: GetSalesContract :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.sales_contracts WHERE id = $1
`

func (q *Queries) GetSalesContract(ctx context.Context, id pgtype.UUID) (SalesContract, error) {
	row := q.db.QueryRow(ctx, getSalesContract, id)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSalesContractBySourceReservation = `-- name: GetSalesContractBySourceReservation :one
SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.sales_contracts WHERE source_reservation_id = $1 LIMIT 1
`

func (q *Queries) GetSalesContractBySourceReservation(ctx context.Context, sourceReservationID pgtype.UUID) (SalesContract, error) {
	row := q.db.QueryRow(ctx, getSalesContractBySourceReservation, sourceReservationID)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkReservationDepositPayment = `-- name: LinkReservationDepositPayment :one
UPDATE public.reservations
SET deposit_payment_id = $2, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type LinkReservationDepositPaymentParams struct {
	ID               pgtype.UUID `json:"id"`
	DepositPaymentID pgtype.UUID `json:"deposit_payment_id"`
}

func (q *Queries) LinkReservationDepositPayment(ctx context.Context, arg LinkReservationDepositPaymentParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, linkReservationDepositPayment, arg.ID, arg.DepositPaymentID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.CustomerID,
		&i.ReservationNo,
		&i.Status,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.DepositAmount,
		&i.DepositCurrency,
		&i.DepositPaymentID,
		&i.QuotedPriceAmount,
		&i.DiscountAmount,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkScheduleLineReceivable = `-- name: LinkScheduleLineReceivable :one
UPDATE public.installment_schedule_lines
SET receivable_id = $2, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at
`

type LinkScheduleLineReceivableParams struct {
	ID           pgtype.UUID `json:"id"`
	ReceivableID pgtype.UUID `json:"receivable_id"`
}

func (q *Queries) LinkScheduleLineReceivable(ctx context.Context, arg LinkScheduleLineReceivableParams) (InstallmentScheduleLine, error) {
	row := q.db.QueryRow(ctx, linkScheduleLineReceivable, arg.ID, arg.ReceivableID)
	var i InstallmentScheduleLine
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.ReceivableID,
		&i.LineNo,
		&i.DueDate,
		&i.LineType,
		&i.Description,
		&i.PrincipalAmount,
		&i.PenaltyAmountAccrued,
		&i.DiscountAmountApplied,
		&i.AmountPaid,
		&i.AmountOutstanding,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractScheduleLinesWithReceivables = `-- name: ListContractScheduleLinesWithReceivables :many
SELECT id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at FROM public.installment_schedule_lines
WHERE sales_contract_id = $1
ORDER BY due_date, line_no
`

func (q *Queries) ListContractScheduleLinesWithReceivables(ctx context.Context, salesContractID pgtype.UUID) ([]InstallmentScheduleLine, error) {
	rows, err := q.db.Query(ctx, listContractScheduleLinesWithReceivables, salesContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentScheduleLine{}
	for rows.Next() {
		var i InstallmentScheduleLine
		if err := rows.Scan(
			&i.ID,
			&i.SalesContractID,
			&i.ReceivableID,
			&i.LineNo,
			&i.DueDate,
			&i.LineType,
			&i.Description,
			&i.PrincipalAmount,
			&i.PenaltyAmountAccrued,
			&i.DiscountAmountApplied,
			&i.AmountPaid,
			&i.AmountOutstanding,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentScheduleLines = `-- name: ListInstallmentScheduleLines :many

SELECT id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at FROM public.installment_schedule_lines
WHERE sales_contract_id = $1
ORDER BY line_no ASC
`

// =============================================================================
// Installment Schedule Lines
// =============================================================================
func (q *Queries) ListInstallmentScheduleLines(ctx context.Context, salesContractID pgtype.UUID) ([]InstallmentScheduleLine, error) {
	rows, err := q.db.Query(ctx, listInstallmentScheduleLines, salesContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstallmentScheduleLine{}
	for rows.Next() {
		var i InstallmentScheduleLine
		if err := rows.Scan(
			&i.ID,
			&i.SalesContractID,
			&i.ReceivableID,
			&i.LineNo,
			&i.DueDate,
			&i.LineType,
			&i.Description,
			&i.PrincipalAmount,
			&i.PenaltyAmountAccrued,
			&i.DiscountAmountApplied,
			&i.AmountPaid,
			&i.AmountOutstanding,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentPlanTemplates = `-- name: ListPaymentPlanTemplates :many

SELECT id, business_entity_id, project_id, code, name, status, frequency_type, installment_count, generation_rule_json, notes, created_at, updated_at FROM public.payment_plan_templates
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5::int OFFSET $4::int
`

type ListPaymentPlanTemplatesParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	Status           pgtype.Text `json:"status"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// =============================================================================
// Payment Plan Templates
// =============================================================================
func (q *Queries) ListPaymentPlanTemplates(ctx context.Context, arg ListPaymentPlanTemplatesParams) ([]PaymentPlanTemplate, error) {
	rows, err := q.db.Query(ctx, listPaymentPlanTemplates,
		arg.BusinessEntityID,
		arg.ProjectID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentPlanTemplate{}
	for rows.Next() {
		var i PaymentPlanTemplate
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.ProjectID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.FrequencyType,
			&i.InstallmentCount,
			&i.GenerationRuleJson,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservations = `-- name: ListReservations :many



SELECT id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.reservations
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR customer_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
ORDER BY created_at DESC
LIMIT $8::int OFFSET $7::int
`

type ListReservationsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	CustomerID       pgtype.UUID `json:"customer_id"`
	Status           pgtype.Text `json:"status"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// backend/db/queries/sales.sql
// =============================================================================
// Sales Domain Queries
// =============================================================================
// =============================================================================
// Reservations
// =============================================================================
func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.CustomerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.ProjectID,
			&i.UnitID,
			&i.CustomerID,
			&i.ReservationNo,
			&i.Status,
			&i.ReservedAt,
			&i.ExpiresAt,
			&i.DepositAmount,
			&i.DepositCurrency,
			&i.DepositPaymentID,
			&i.QuotedPriceAmount,
			&i.DiscountAmount,
			&i.Notes,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesContractParties = `-- name: ListSalesContractParties :many

SELECT id, sales_contract_id, party_id, role, is_primary, effective_from, effective_to, status, created_at, updated_at FROM public.sales_contract_parties
WHERE sales_contract_id = $1
ORDER BY is_primary DESC, effective_from DESC
`

// =============================================================================
// Sales Contract Parties
// =============================================================================
func (q *Queries) ListSalesContractParties(ctx context.Context, salesContractID pgtype.UUID) ([]SalesContractParty, error) {
	rows, err := q.db.Query(ctx, listSalesContractParties, salesContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesContractParty{}
	for rows.Next() {
		var i SalesContractParty
		if err := rows.Scan(
			&i.ID,
			&i.SalesContractID,
			&i.PartyID,
			&i.Role,
			&i.IsPrimary,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesContracts = `-- name: ListSalesContracts :many

SELECT id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at FROM public.sales_contracts
WHERE ($1::uuid IS NULL OR business_entity_id = $1::uuid)
  AND ($2::uuid IS NULL OR branch_id = $2::uuid)
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
  AND ($4::uuid IS NULL OR unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR primary_buyer_id = $5::uuid)
  AND ($6::text IS NULL OR status = $6::text)
ORDER BY created_at DESC
LIMIT $8::int OFFSET $7::int
`

type ListSalesContractsParams struct {
	BusinessEntityID pgtype.UUID `json:"business_entity_id"`
	BranchID         pgtype.UUID `json:"branch_id"`
	ProjectID        pgtype.UUID `json:"project_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	PrimaryBuyerID   pgtype.UUID `json:"primary_buyer_id"`
	Status           pgtype.Text `json:"status"`
	Offset           int32       `json:"offset"`
	Limit            int32       `json:"limit"`
}

// =============================================================================
// Sales Contracts
// =============================================================================
func (q *Queries) ListSalesContracts(ctx context.Context, arg ListSalesContractsParams) ([]SalesContract, error) {
	rows, err := q.db.Query(ctx, listSalesContracts,
		arg.BusinessEntityID,
		arg.BranchID,
		arg.ProjectID,
		arg.UnitID,
		arg.PrimaryBuyerID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesContract{}
	for rows.Next() {
		var i SalesContract
		if err := rows.Scan(
			&i.ID,
			&i.BusinessEntityID,
			&i.BranchID,
			&i.ProjectID,
			&i.UnitID,
			&i.PrimaryBuyerID,
			&i.SourceReservationID,
			&i.ContractNo,
			&i.Status,
			&i.ContractDate,
			&i.EffectiveDate,
			&i.SalePriceAmount,
			&i.SalePriceCurrency,
			&i.DiscountAmount,
			&i.NetContractAmount,
			&i.DownPaymentAmount,
			&i.FinancedAmount,
			&i.PaymentPlanTemplateID,
			&i.HandoverDatePlanned,
			&i.HandoverDateActual,
			&i.Notes,
			&i.CreatedByUserID,
			&i.ApprovedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOwnershipTransferCompletion = `-- name: SetOwnershipTransferCompletion :one
UPDATE public.ownership_transfers
SET status = 'completed',
    completed_by_user_id = $2,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at
`

type SetOwnershipTransferCompletionParams struct {
	ID                pgtype.UUID `json:"id"`
	CompletedByUserID pgtype.UUID `json:"completed_by_user_id"`
}

func (q *Queries) SetOwnershipTransferCompletion(ctx context.Context, arg SetOwnershipTransferCompletionParams) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, setOwnershipTransferCompletion, arg.ID, arg.CompletedByUserID)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstallmentScheduleLine = `-- name: UpdateInstallmentScheduleLine :one
UPDATE public.installment_schedule_lines SET
    due_date = COALESCE($1::date, due_date),
    description = COALESCE($2::text, description),
    principal_amount = COALESCE($3::numeric, principal_amount),
    penalty_amount_accrued = COALESCE($4::numeric, penalty_amount_accrued),
    discount_amount_applied = COALESCE($5::numeric, discount_amount_applied),
    status = COALESCE($6::text, status),
    updated_at = timezone('utc', now())
WHERE id = $7::uuid
RETURNING id, sales_contract_id, receivable_id, line_no, due_date, line_type, description, principal_amount, penalty_amount_accrued, discount_amount_applied, amount_paid, amount_outstanding, status, created_at, updated_at
`

type UpdateInstallmentScheduleLineParams struct {
	DueDate               pgtype.Date    `json:"due_date"`
	Description           pgtype.Text    `json:"description"`
	PrincipalAmount       pgtype.Numeric `json:"principal_amount"`
	PenaltyAmountAccrued  pgtype.Numeric `json:"penalty_amount_accrued"`
	DiscountAmountApplied pgtype.Numeric `json:"discount_amount_applied"`
	Status                pgtype.Text    `json:"status"`
	ID                    pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateInstallmentScheduleLine(ctx context.Context, arg UpdateInstallmentScheduleLineParams) (InstallmentScheduleLine, error) {
	row := q.db.QueryRow(ctx, updateInstallmentScheduleLine,
		arg.DueDate,
		arg.Description,
		arg.PrincipalAmount,
		arg.PenaltyAmountAccrued,
		arg.DiscountAmountApplied,
		arg.Status,
		arg.ID,
	)
	var i InstallmentScheduleLine
	err := row.Scan(
		&i.ID,
		&i.SalesContractID,
		&i.ReceivableID,
		&i.LineNo,
		&i.DueDate,
		&i.LineType,
		&i.Description,
		&i.PrincipalAmount,
		&i.PenaltyAmountAccrued,
		&i.DiscountAmountApplied,
		&i.AmountPaid,
		&i.AmountOutstanding,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOwnershipTransferApprovalRequest = `-- name: UpdateOwnershipTransferApprovalRequest :one
UPDATE public.ownership_transfers
SET approval_request_id = $2, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at
`

type UpdateOwnershipTransferApprovalRequestParams struct {
	ID                pgtype.UUID `json:"id"`
	ApprovalRequestID pgtype.UUID `json:"approval_request_id"`
}

func (q *Queries) UpdateOwnershipTransferApprovalRequest(ctx context.Context, arg UpdateOwnershipTransferApprovalRequestParams) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, updateOwnershipTransferApprovalRequest, arg.ID, arg.ApprovalRequestID)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOwnershipTransferStatus = `-- name: UpdateOwnershipTransferStatus :one
UPDATE public.ownership_transfers
SET status = $2, updated_at = timezone('utc', now())
WHERE id = $1 AND status = $3
RETURNING id, business_entity_id, branch_id, project_id, unit_id, sales_contract_id, approval_request_id, transfer_type, from_party_id, to_party_id, effective_date, financial_treatment, transfer_fee_amount, transfer_fee_currency, notes, status, requested_by_user_id, approved_by_user_id, completed_by_user_id, created_at, updated_at
`

type UpdateOwnershipTransferStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) UpdateOwnershipTransferStatus(ctx context.Context, arg UpdateOwnershipTransferStatusParams) (OwnershipTransfer, error) {
	row := q.db.QueryRow(ctx, updateOwnershipTransferStatus, arg.ID, arg.Status, arg.Status_2)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.SalesContractID,
		&i.ApprovalRequestID,
		&i.TransferType,
		&i.FromPartyID,
		&i.ToPartyID,
		&i.EffectiveDate,
		&i.FinancialTreatment,
		&i.TransferFeeAmount,
		&i.TransferFeeCurrency,
		&i.Notes,
		&i.Status,
		&i.RequestedByUserID,
		&i.ApprovedByUserID,
		&i.CompletedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :one
UPDATE public.reservations
SET status = $2, updated_at = timezone('utc', now())
WHERE id = $1 AND status = $3
RETURNING id, business_entity_id, branch_id, project_id, unit_id, customer_id, reservation_no, status, reserved_at, expires_at, deposit_amount, deposit_currency, deposit_payment_id, quoted_price_amount, discount_amount, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateReservationStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationStatus, arg.ID, arg.Status, arg.Status_2)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.CustomerID,
		&i.ReservationNo,
		&i.Status,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.DepositAmount,
		&i.DepositCurrency,
		&i.DepositPaymentID,
		&i.QuotedPriceAmount,
		&i.DiscountAmount,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesContract = `-- name: UpdateSalesContract :one
UPDATE public.sales_contracts SET
    sale_price_amount = COALESCE($1::numeric, sale_price_amount),
    discount_amount = COALESCE($2::numeric, discount_amount),
    net_contract_amount = COALESCE($3::numeric, net_contract_amount),
    down_payment_amount = COALESCE($4::numeric, down_payment_amount),
    financed_amount = COALESCE($5::numeric, financed_amount),
    payment_plan_template_id = COALESCE($6::uuid, payment_plan_template_id),
    handover_date_planned = COALESCE($7::date, handover_date_planned),
    handover_date_actual = COALESCE($8::date, handover_date_actual),
    notes = COALESCE($9::text, notes),
    updated_at = timezone('utc', now())
WHERE id = $10::uuid AND status = 'draft'
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateSalesContractParams struct {
	SalePriceAmount       pgtype.Numeric `json:"sale_price_amount"`
	DiscountAmount        pgtype.Numeric `json:"discount_amount"`
	NetContractAmount     pgtype.Numeric `json:"net_contract_amount"`
	DownPaymentAmount     pgtype.Numeric `json:"down_payment_amount"`
	FinancedAmount        pgtype.Numeric `json:"financed_amount"`
	PaymentPlanTemplateID pgtype.UUID    `json:"payment_plan_template_id"`
	HandoverDatePlanned   pgtype.Date    `json:"handover_date_planned"`
	HandoverDateActual    pgtype.Date    `json:"handover_date_actual"`
	Notes                 pgtype.Text    `json:"notes"`
	ID                    pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateSalesContract(ctx context.Context, arg UpdateSalesContractParams) (SalesContract, error) {
	row := q.db.QueryRow(ctx, updateSalesContract,
		arg.SalePriceAmount,
		arg.DiscountAmount,
		arg.NetContractAmount,
		arg.DownPaymentAmount,
		arg.FinancedAmount,
		arg.PaymentPlanTemplateID,
		arg.HandoverDatePlanned,
		arg.HandoverDateActual,
		arg.Notes,
		arg.ID,
	)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesContractPrimaryBuyer = `-- name: UpdateSalesContractPrimaryBuyer :one
UPDATE public.sales_contracts
SET primary_buyer_id = $2, updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateSalesContractPrimaryBuyerParams struct {
	ID             pgtype.UUID `json:"id"`
	PrimaryBuyerID pgtype.UUID `json:"primary_buyer_id"`
}

func (q *Queries) UpdateSalesContractPrimaryBuyer(ctx context.Context, arg UpdateSalesContractPrimaryBuyerParams) (SalesContract, error) {
	row := q.db.QueryRow(ctx, updateSalesContractPrimaryBuyer, arg.ID, arg.PrimaryBuyerID)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesContractStatus = `-- name: UpdateSalesContractStatus :one
UPDATE public.sales_contracts
SET status = $2, updated_at = timezone('utc', now())
WHERE id = $1 AND status = $3
RETURNING id, business_entity_id, branch_id, project_id, unit_id, primary_buyer_id, source_reservation_id, contract_no, status, contract_date, effective_date, sale_price_amount, sale_price_currency, discount_amount, net_contract_amount, down_payment_amount, financed_amount, payment_plan_template_id, handover_date_planned, handover_date_actual, notes, created_by_user_id, approved_by_user_id, created_at, updated_at
`

type UpdateSalesContractStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Status_2 string      `json:"status_2"`
}

func (q *Queries) UpdateSalesContractStatus(ctx context.Context, arg UpdateSalesContractStatusParams) (SalesContract, error) {
	row := q.db.QueryRow(ctx, updateSalesContractStatus, arg.ID, arg.Status, arg.Status_2)
	var i SalesContract
	err := row.Scan(
		&i.ID,
		&i.BusinessEntityID,
		&i.BranchID,
		&i.ProjectID,
		&i.UnitID,
		&i.PrimaryBuyerID,
		&i.SourceReservationID,
		&i.ContractNo,
		&i.Status,
		&i.ContractDate,
		&i.EffectiveDate,
		&i.SalePriceAmount,
		&i.SalePriceCurrency,
		&i.DiscountAmount,
		&i.NetContractAmount,
		&i.DownPaymentAmount,
		&i.FinancedAmount,
		&i.PaymentPlanTemplateID,
		&i.HandoverDatePlanned,
		&i.HandoverDateActual,
		&i.Notes,
		&i.CreatedByUserID,
		&i.ApprovedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
