// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodoRLS = `-- name: CreateTodoRLS :one
INSERT INTO public.todos (task)
VALUES ($1)
RETURNING id, user_id, task, is_complete, created_at
`

func (q *Queries) CreateTodoRLS(ctx context.Context, task string) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodoRLS, task)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.IsComplete,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTodoRLS = `-- name: DeleteTodoRLS :exec
DELETE FROM public.todos
WHERE id = $1
`

func (q *Queries) DeleteTodoRLS(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodoRLS, id)
	return err
}

const getTodoByIDRLS = `-- name: GetTodoByIDRLS :one
SELECT id, user_id, task, is_complete, created_at FROM public.todos
WHERE id = $1
`

func (q *Queries) GetTodoByIDRLS(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByIDRLS, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.IsComplete,
		&i.CreatedAt,
	)
	return i, err
}

const getTodosRLS = `-- name: GetTodosRLS :many

SELECT id, user_id, task, is_complete, created_at FROM public.todos
ORDER BY created_at DESC
`

// RLS-based queries (rely on auth.uid() via GUC variables)
// These must be used within a transaction with GUC injection
func (q *Queries) GetTodosRLS(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosRLS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Task,
			&i.IsComplete,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodoRLS = `-- name: ToggleTodoRLS :exec
UPDATE public.todos
SET is_complete = NOT is_complete
WHERE id = $1
`

func (q *Queries) ToggleTodoRLS(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, toggleTodoRLS, id)
	return err
}
