// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO public.todos (user_id, task)
VALUES ($1, $2)
RETURNING id, user_id, task, is_complete, created_at
`

type CreateTodoParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Task   string      `json:"task"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.UserID, arg.Task)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Task,
		&i.IsComplete,
		&i.CreatedAt,
	)
	return i, err
}

const getTodosForUser = `-- name: GetTodosForUser :many
SELECT id, user_id, task, is_complete, created_at FROM public.todos
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTodosForUser(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, getTodosForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Todo{}
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Task,
			&i.IsComplete,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTodo = `-- name: ToggleTodo :exec
UPDATE public.todos
SET is_complete = NOT is_complete
WHERE id = $1 AND user_id = $2
`

type ToggleTodoParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleTodo(ctx context.Context, arg ToggleTodoParams) error {
	_, err := q.db.Exec(ctx, toggleTodo, arg.ID, arg.UserID)
	return err
}
